// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

// MARK: Windows.Foundation.IReference`1<WinRTComponent.MinimalEnum>

@_exported import enum WindowsRuntime.WindowsFoundation_IReferenceBinding

// MARK: Windows.Foundation.IReference`1<WinRTComponent.MinimalStruct>

@_exported import enum WindowsRuntime.WindowsFoundation_IReferenceBinding

// MARK: Windows.Foundation.IReference`1<Int32>

@_exported import enum WindowsRuntime.WindowsFoundation_IReferenceBinding