// Generated by swift-winrt
// swiftlint:disable all

import UWP

public typealias IIterable<T> = WindowsFoundationCollections_IIterable<T>

public protocol IIterableProtocol<T>: WindowsFoundationCollections_IIterableProtocol {
}

public typealias IIterableBinding = WindowsFoundationCollections_IIterableBinding
public typealias IIterator<T> = WindowsFoundationCollections_IIterator<T>

public protocol IIteratorProtocol<T>: WindowsFoundationCollections_IIteratorProtocol {
}

public typealias IIteratorBinding = WindowsFoundationCollections_IIteratorBinding
public typealias IVectorView<T> = WindowsFoundationCollections_IVectorView<T>

public protocol IVectorViewProtocol<T>: WindowsFoundationCollections_IVectorViewProtocol {
}

public typealias IVectorViewBinding = WindowsFoundationCollections_IVectorViewBinding
public typealias IVector<T> = WindowsFoundationCollections_IVector<T>

public protocol IVectorProtocol<T>: WindowsFoundationCollections_IVectorProtocol {
}

public typealias IVectorBinding = WindowsFoundationCollections_IVectorBinding