// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

extension Enum: WindowsRuntime.OpenEnumBinding {
    public static let typeName = "WinRTComponent.Enum"

    public static var ireferenceID: COM.COMInterfaceID {
        COMInterfaceID(0x1EAA21D1, 0x5789, 0x5FA5, 0x937C, 0xE01F2FF1432B)
    }

    public static var ireferenceArrayID: COM.COMInterfaceID {
        COMInterfaceID(0x2AA3764B, 0x094B, 0x5AC7, 0x9EAB, 0xC53C42898620)
    }
}