// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

extension Flags: WindowsRuntime.OpenEnumBinding {
    public static let typeName = "WinRTComponent.Flags"

    public static var ireferenceID: COM.COMInterfaceID {
        COMInterfaceID(0xA2735C74, 0xADAB, 0x55F5, 0xA490, 0xBF557A242E5A)
    }

    public static var ireferenceArrayID: COM.COMInterfaceID {
        COMInterfaceID(0x70CA786C, 0xDF6D, 0x579B, 0xB278, 0x3F347C2C703C)
    }
}