// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public class Int32WrapperBinding: WindowsRuntime.ActivatableClassBinding {
    public typealias SwiftObject = Int32Wrapper
    public typealias ABIStruct = SWRT_WinRTComponent_IInt32Wrapper

    public static let typeName = "WinRTComponent.Int32Wrapper"

    public static var interfaceID: COM.COMInterfaceID {
        uuidof(ABIStruct.self)
    }

    public static func _wrap(_ reference: consuming ABIReference) -> SwiftObject {
        Int32Wrapper(_wrapping: consume reference)
    }
}