// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public enum IReturnArgumentBinding: WindowsRuntime.InterfaceBinding {
    public typealias SwiftObject = IReturnArgument
    public typealias ABIStruct = SWRT_WinRTComponent_IReturnArgument

    public static let typeName = "WinRTComponent.IReturnArgument"

    public static var interfaceID: COM.COMInterfaceID {
        uuidof(ABIStruct.self)
    }

    public static func _wrap(_ reference: consuming ABIReference) -> SwiftObject {
        Import(_wrapping: consume reference)
    }

    private final class Import: WinRTImport<IReturnArgumentBinding>, IReturnArgumentProtocol {
        public func int32(_ value: Swift.Int32) throws -> Swift.Int32 {
            try _interop.int32(value)
        }

        public func string(_ value: Swift.String) throws -> Swift.String {
            try _interop.string(value)
        }

        public func object(_ value: WindowsRuntime.IInspectable?) throws -> WindowsRuntime.IInspectable {
            try COM.NullResult.unwrap(_interop.object(value))
        }

        public func `enum`(_ value: MinimalEnum) throws -> MinimalEnum {
            try _interop.enum(value)
        }

        public func `struct`(_ value: MinimalStruct) throws -> MinimalStruct {
            try _interop.struct(value)
        }

        public func interface(_ value: IMinimalInterface?) throws -> IMinimalInterface {
            try COM.NullResult.unwrap(_interop.interface(value))
        }

        public func `class`(_ value: MinimalClass?) throws -> MinimalClass {
            try COM.NullResult.unwrap(_interop.class(value))
        }

        public func delegate(_ value: MinimalDelegate?) throws -> MinimalDelegate {
            try COM.NullResult.unwrap(_interop.delegate(value))
        }

        public func array(_ value: [Swift.String]) throws -> [Swift.String] {
            try _interop.array(value)
        }

        public func reference(_ value: Swift.Int32?) throws -> Swift.Int32? {
            try _interop.reference(value)
        }
    }

    public static var virtualTablePointer: UnsafeRawPointer {
        .init(withUnsafePointer(to: &virtualTable) { $0 })
    }

    private static var virtualTable = SWRT_WinRTComponent_IReturnArgument_VirtualTable(
        QueryInterface: { IUnknownVirtualTable.QueryInterface($0, $1, $2) },
        AddRef: { IUnknownVirtualTable.AddRef($0) },
        Release: { IUnknownVirtualTable.Release($0) },
        GetIids: { IInspectableVirtualTable.GetIids($0, $1, $2) },
        GetRuntimeClassName: { IInspectableVirtualTable.GetRuntimeClassName($0, $1) },
        GetTrustLevel: { IInspectableVirtualTable.GetTrustLevel($0, $1) },
        Int32: { this, value, _result in _implement(this) { this in
            guard let _result else { throw COM.COMError.pointer }
            _result.pointee = try this.int32(value)
        } },
        String: { this, value, _result in _implement(this) { this in
            guard let _result else { throw COM.COMError.pointer }
            let value_swift = WindowsRuntime.StringBinding.fromABI(value)
            let _result_swift = try this.string(value_swift)
            _result.pointee = try WindowsRuntime.StringBinding.toABI(_result_swift)
        } },
        Object: { this, value, _result in _implement(this) { this in
            guard let _result else { throw COM.COMError.pointer }
            let value_swift = WindowsRuntime.IInspectableBinding.fromABI(value)
            let _result_swift = try COM.NullResult.`catch`(try this.object(value_swift))
            _result.pointee = try WindowsRuntime.IInspectableBinding.toABI(_result_swift)
        } },
        Enum: { this, value, _result in _implement(this) { this in
            guard let _result else { throw COM.COMError.pointer }
            let value_swift = MinimalEnum.fromABI(value)
            let _result_swift = try this.enum(value_swift)
            _result.pointee = MinimalEnum.toABI(_result_swift)
        } },
        Struct: { this, value, _result in _implement(this) { this in
            guard let _result else { throw COM.COMError.pointer }
            let value_swift = MinimalStruct.fromABI(value)
            let _result_swift = try this.struct(value_swift)
            _result.pointee = MinimalStruct.toABI(_result_swift)
        } },
        Interface: { this, value, _result in _implement(this) { this in
            guard let _result else { throw COM.COMError.pointer }
            let value_swift = IMinimalInterfaceBinding.fromABI(value)
            let _result_swift = try COM.NullResult.`catch`(try this.interface(value_swift))
            _result.pointee = try IMinimalInterfaceBinding.toABI(_result_swift)
        } },
        Class: { this, value, _result in _implement(this) { this in
            guard let _result else { throw COM.COMError.pointer }
            let value_swift = MinimalClassBinding.fromABI(value)
            let _result_swift = try COM.NullResult.`catch`(try this.class(value_swift))
            _result.pointee = try MinimalClassBinding.toABI(_result_swift)
        } },
        Delegate: { this, value, _result in _implement(this) { this in
            guard let _result else { throw COM.COMError.pointer }
            let value_swift = MinimalDelegateBinding.fromABI(value)
            let _result_swift = try COM.NullResult.`catch`(try this.delegate(value_swift))
            _result.pointee = try MinimalDelegateBinding.toABI(_result_swift)
        } },
        Array: { this, valueLength, value, _resultLength, _result in _implement(this) { this in
            guard let _result else { throw COM.COMError.pointer }
            let value_swift = WindowsRuntime.ArrayBinding<WindowsRuntime.StringBinding>.fromABI(pointer: value, count: valueLength)
            let _result_swift = try this.array(value_swift)
            fatalError("Not implemented: out arrays")
        } },
        Reference: { this, value, _result in _implement(this) { this in
            guard let _result else { throw COM.COMError.pointer }
            let value_swift = WindowsRuntime.Int32Binding.IReferenceToOptional.fromABI(value)
            let _result_swift = try this.reference(value_swift)
            _result.pointee = try WindowsRuntime.Int32Binding.IReferenceToOptional.toABI(_result_swift)
        } }
    )
}