// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

extension LeafStruct: WindowsRuntime.StructBinding {
    public typealias SwiftValue = Self
    public typealias ABIValue = SWRT_WinRTComponent_LeafStruct

    public static let typeName = "WinRTComponent.LeafStruct"

    public static var ireferenceID: COM.COMInterfaceID {
        COMInterfaceID(0x5A9C76DF, 0xE570, 0x521A, 0x899F, 0x641B4DD98548)
    }

    public static var ireferenceArrayID: COM.COMInterfaceID {
        COMInterfaceID(0x9A8B3991, 0x23FA, 0x5FF0, 0xA348, 0xDA38618C8FF7)
    }

    public static var abiDefaultValue: SWRT_WinRTComponent_LeafStruct {
        .init()
    }

    public static func fromABI(_ value: SWRT_WinRTComponent_LeafStruct) -> Self {
        .init(
            int32: value.Int32,
            string: WindowsRuntime.StringBinding.fromABI(value.String),
            reference: WindowsRuntime.Int32Binding.IReferenceToOptional.fromABI(value.Reference)
        )
    }

    public static func toABI(_ value: Self) throws -> SWRT_WinRTComponent_LeafStruct {
        .init(
            Int32: value.int32,
            String: try WindowsRuntime.StringBinding.toABI(value.string),
            Reference: try WindowsRuntime.Int32Binding.IReferenceToOptional.toABI(value.reference)
        )
    }

    public static func release(_ value: inout SWRT_WinRTComponent_LeafStruct) {
        WindowsRuntime.StringBinding.release(&value.String)
        WindowsRuntime.Int32Binding.IReferenceToOptional.release(&value.Reference)
    }
}