// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public class ManualAsyncOperationBinding: WindowsRuntime.ActivatableClassBinding {
    public typealias SwiftObject = ManualAsyncOperation
    public typealias ABIStruct = SWRT_WinRTComponent_IManualAsyncOperation

    public static let typeName = "WinRTComponent.ManualAsyncOperation"

    public static var interfaceID: COM.COMInterfaceID {
        uuidof(ABIStruct.self)
    }

    public static func _wrap(_ reference: consuming ABIReference) -> SwiftObject {
        ManualAsyncOperation(_wrapping: consume reference)
    }
}