// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public class MinimalClassBinding: WindowsRuntime.ActivatableClassBinding {
    public typealias SwiftObject = MinimalClass
    public typealias ABIStruct = SWRT_WinRTComponent_IMinimalClass

    public static let typeName = "WinRTComponent.MinimalClass"

    public static var interfaceID: COM.COMInterfaceID {
        uuidof(ABIStruct.self)
    }

    public static func _wrap(_ reference: consuming ABIReference) -> SwiftObject {
        MinimalClass(_wrapping: consume reference)
    }
}