// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

extension MinimalStruct: WindowsRuntime.StructBinding, COM.PODBinding {
    public typealias SwiftValue = Self
    public typealias ABIValue = SWRT_WinRTComponent_MinimalStruct

    public static let typeName = "WinRTComponent.MinimalStruct"

    public static var ireferenceID: COM.COMInterfaceID {
        COMInterfaceID(0x6E789639, 0xF81E, 0x5107, 0xA96C, 0x9A9ABA3A6DFD)
    }

    public static var ireferenceArrayID: COM.COMInterfaceID {
        COMInterfaceID(0xF4100C3B, 0x40F1, 0x55B1, 0xBE47, 0xE065A9698326)
    }

    public static var abiDefaultValue: SWRT_WinRTComponent_MinimalStruct {
        .init()
    }

    public static func fromABI(_ value: SWRT_WinRTComponent_MinimalStruct) -> Self {
        .init(
            field: value.Field
        )
    }

    public static func toABI(_ value: Self) -> SWRT_WinRTComponent_MinimalStruct {
        .init(
            Field: value.field
        )
    }
}