// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

extension MinimalEnum: WindowsRuntime.OpenEnumBinding {
    public static let typeName = "WinRTComponent.MinimalEnum"

    public static var ireferenceID: COM.COMInterfaceID {
        COMInterfaceID(0x95B2661C, 0x4079, 0x5135, 0xAEF9, 0x44BEB78E4135)
    }

    public static var ireferenceArrayID: COM.COMInterfaceID {
        COMInterfaceID(0xAD9E1600, 0x4423, 0x5B12, 0x8708, 0xE7D93004B14D)
    }
}