// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public class ObjectReferencerBinding: WindowsRuntime.ActivatableClassBinding {
    public typealias SwiftObject = ObjectReferencer
    public typealias ABIStruct = SWRT_WinRTComponent_IObjectReferencer

    public static let typeName = "WinRTComponent.ObjectReferencer"

    public static var interfaceID: COM.COMInterfaceID {
        uuidof(ABIStruct.self)
    }

    public static func _wrap(_ reference: consuming ABIReference) -> SwiftObject {
        ObjectReferencer(_wrapping: consume reference)
    }
}