// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public class OverloadedSumBinding: WindowsRuntime.ActivatableClassBinding {
    public typealias SwiftObject = OverloadedSum
    public typealias ABIStruct = SWRT_WinRTComponent_IOverloadedSum

    public static let typeName = "WinRTComponent.OverloadedSum"

    public static var interfaceID: COM.COMInterfaceID {
        uuidof(ABIStruct.self)
    }

    public static func _wrap(_ reference: consuming ABIReference) -> SwiftObject {
        OverloadedSum(_wrapping: consume reference)
    }
}