// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

extension SwiftEnum: WindowsRuntime.ClosedEnumBinding {
    public static let typeName = "WinRTComponent.SwiftEnum"

    public static var ireferenceID: COM.COMInterfaceID {
        COMInterfaceID(0x326A4A37, 0xBD7E, 0x57B4, 0xA6F3, 0x552DF93417AC)
    }

    public static var ireferenceArrayID: COM.COMInterfaceID {
        COMInterfaceID(0x81F98566, 0x3975, 0x57BF, 0xAFC0, 0x7E0EBBE18E04)
    }
}