// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public class WeakReferencerBinding: WindowsRuntime.ActivatableClassBinding {
    public typealias SwiftObject = WeakReferencer
    public typealias ABIStruct = SWRT_WinRTComponent_IWeakReferencer

    public static let typeName = "WinRTComponent.WeakReferencer"

    public static var interfaceID: COM.COMInterfaceID {
        uuidof(ABIStruct.self)
    }

    public static func _wrap(_ reference: consuming ABIReference) -> SwiftObject {
        WeakReferencer(_wrapping: consume reference)
    }
}