// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public func uuidof(_: SWRT_WinRTComponent_IOutputArgumentStatics.Type) -> COM.COMInterfaceID {
    COMInterfaceID(0x1AD6E25C, 0x8597, 0x588C, 0xA39B, 0xD18E8FCAE413)
}

extension COM.COMInterop where ABIStruct == SWRT_WinRTComponent_IOutputArgumentStatics {
    public func create() throws -> IOutputArgument? {
        var _result: Swift.UnsafeMutablePointer<SWRT_WinRTComponent_IOutputArgument>? = nil
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.Create(this, &_result))
        return IOutputArgumentBinding.fromABI(consuming: &_result)
    }

    public func createProxy(_ inner: IOutputArgument?) throws -> IOutputArgument? {
        var inner_abi = try IOutputArgumentBinding.toABI(inner)
        defer { IOutputArgumentBinding.release(&inner_abi) }
        var _result: Swift.UnsafeMutablePointer<SWRT_WinRTComponent_IOutputArgument>? = nil
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.CreateProxy(this, inner_abi, &_result))
        return IOutputArgumentBinding.fromABI(consuming: &_result)
    }
}