// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public func uuidof(_: SWRT_WinRTComponent_IEventSource.Type) -> COM.COMInterfaceID {
    COMInterfaceID(0x9C618D12, 0x4095, 0x58E5, 0x8509, 0xAD84F65D8EB6)
}

extension COM.COMInterop where ABIStruct == SWRT_WinRTComponent_IEventSource {
    public func add_Event(_ handler: MinimalDelegate?) throws -> WindowsRuntime.EventRegistrationToken {
        var handler_abi = try MinimalDelegateBinding.toABI(handler)
        defer { MinimalDelegateBinding.release(&handler_abi) }
        var _result: SWRT_EventRegistrationToken = .init()
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.add_Event(this, handler_abi, &_result))
        return WindowsRuntime.EventRegistrationToken.fromABI(_result)
    }

    public func remove_Event(_ token: WindowsRuntime.EventRegistrationToken) throws {
        let token_abi = WindowsRuntime.EventRegistrationToken.toABI(token)
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.remove_Event(this, token_abi))
    }

    public func fire() throws {
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.Fire(this))
    }
}