// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public func uuidof(_: SWRT_WinRTComponent_IMinimalBaseClassFactory.Type) -> COM.COMInterfaceID {
    COMInterfaceID(0x8F98A53C, 0xE26E, 0x548A, 0x89FE, 0x88708F732FE9)
}

extension COM.COMInterop where ABIStruct == SWRT_WinRTComponent_IMinimalBaseClassFactory {
    public func createInstance(_ baseInterface: WindowsRuntime.IInspectablePointer?, _ innerInterface: inout WindowsRuntime.IInspectablePointer?) throws -> COM.COMReference<SWRT_WinRTComponent_IMinimalBaseClass> {
        var _result: Swift.UnsafeMutablePointer<SWRT_WinRTComponent_IMinimalBaseClass>? = nil
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.CreateInstance(this, baseInterface, &innerInterface, &_result))
        guard let _result else { throw COMError.pointer }
        return COM.COMReference(transferringRef: _result)
    }
}