// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public func uuidof(_: SWRT_WinRTComponent_IManualAsyncOperation.Type) -> COM.COMInterfaceID {
    COMInterfaceID(0xAAE9AF9F, 0x689E, 0x5D25, 0x8FD6, 0x0FDA150F34FA)
}

extension COM.COMInterop where ABIStruct == SWRT_WinRTComponent_IManualAsyncOperation {
    public func complete(_ result: Swift.Int32) throws {
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.Complete(this, result))
    }

    public func completeWithError(_ errorCode: COM.HResult) throws {
        let errorCode_abi = COM.HResultBinding.toABI(errorCode)
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.CompleteWithError(this, errorCode_abi))
    }
}