// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public func uuidof(_: SWRT_WinRTComponent_IReferenceBoxingStatics.Type) -> COM.COMInterfaceID {
    COMInterfaceID(0x75CAF74E, 0xCCAD, 0x56F8, 0x885F, 0xC8D3778209C5)
}

extension COM.COMInterop where ABIStruct == SWRT_WinRTComponent_IReferenceBoxingStatics {
    public func boxInt32(_ value: Swift.Int32) throws -> Swift.Int32? {
        var _result: Swift.UnsafeMutablePointer<SWRT_WindowsFoundation_IReference>? = nil
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.BoxInt32(this, value, &_result))
        return WindowsRuntime.Int32Binding.IReferenceToOptional.fromABI(consuming: &_result)
    }

    public func unboxInt32(_ value: Swift.Int32?) throws -> Swift.Int32 {
        var value_abi = try WindowsRuntime.Int32Binding.IReferenceToOptional.toABI(value)
        defer { WindowsRuntime.Int32Binding.IReferenceToOptional.release(&value_abi) }
        var _result: Swift.Int32 = 0
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.UnboxInt32(this, value_abi, &_result))
        return _result
    }

    public func boxMinimalEnum(_ value: MinimalEnum) throws -> MinimalEnum? {
        let value_abi = MinimalEnum.toABI(value)
        var _result: Swift.UnsafeMutablePointer<SWRT_WindowsFoundation_IReference>? = nil
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.BoxMinimalEnum(this, value_abi, &_result))
        return WindowsRuntime.IReferenceToOptionalBinding<MinimalEnum>.fromABI(consuming: &_result)
    }

    public func unboxMinimalEnum(_ value: MinimalEnum?) throws -> MinimalEnum {
        var value_abi = try WindowsRuntime.IReferenceToOptionalBinding<MinimalEnum>.toABI(value)
        defer { WindowsRuntime.IReferenceToOptionalBinding<MinimalEnum>.release(&value_abi) }
        var _result: SWRT_WinRTComponent_MinimalEnum = .init()
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.UnboxMinimalEnum(this, value_abi, &_result))
        return MinimalEnum.fromABI(_result)
    }

    public func boxMinimalStruct(_ value: MinimalStruct) throws -> MinimalStruct? {
        let value_abi = MinimalStruct.toABI(value)
        var _result: Swift.UnsafeMutablePointer<SWRT_WindowsFoundation_IReference>? = nil
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.BoxMinimalStruct(this, value_abi, &_result))
        return WindowsRuntime.IReferenceToOptionalBinding<MinimalStruct>.fromABI(consuming: &_result)
    }

    public func unboxMinimalStruct(_ value: MinimalStruct?) throws -> MinimalStruct {
        var value_abi = try WindowsRuntime.IReferenceToOptionalBinding<MinimalStruct>.toABI(value)
        defer { WindowsRuntime.IReferenceToOptionalBinding<MinimalStruct>.release(&value_abi) }
        var _result: SWRT_WinRTComponent_MinimalStruct = .init()
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.UnboxMinimalStruct(this, value_abi, &_result))
        return MinimalStruct.fromABI(_result)
    }
}