// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public func uuidof(_: SWRT_WinRTComponent_IMinimalInterfaceFactoryStatics.Type) -> COM.COMInterfaceID {
    COMInterfaceID(0x71F318BA, 0x1D0E, 0x52B7, 0x80E9, 0xE990FD97AFDF)
}

extension COM.COMInterop where ABIStruct == SWRT_WinRTComponent_IMinimalInterfaceFactoryStatics {
    public func create() throws -> IMinimalInterface? {
        var _result: Swift.UnsafeMutablePointer<SWRT_WinRTComponent_IMinimalInterface>? = nil
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.Create(this, &_result))
        return IMinimalInterfaceBinding.fromABI(consuming: &_result)
    }
}