// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public func uuidof(_: SWRT_WinRTComponent_IForCustomActivationFactoryResolutionStatics.Type) -> COM.COMInterfaceID {
    COMInterfaceID(0xF029DA63, 0xC460, 0x52B6, 0x8F37, 0x1655CFD94029)
}

extension COM.COMInterop where ABIStruct == SWRT_WinRTComponent_IForCustomActivationFactoryResolutionStatics {
    public func method() throws {
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.Method(this))
    }
}