// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public func uuidof(_: SWRT_WinRTComponent_IMinimalClass.Type) -> COM.COMInterfaceID {
    COMInterfaceID(0x2FEBA45D, 0xBBF4, 0x5AA0, 0x89C4, 0x7CE770C6886C)
}

extension COM.COMInterop where ABIStruct == SWRT_WinRTComponent_IMinimalClass {
    public func method() throws {
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.Method(this))
    }
}