// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public func uuidof(_: SWRT_WinRTComponent_IInt32Wrapper.Type) -> COM.COMInterfaceID {
    COMInterfaceID(0x4C855DE6, 0x81A2, 0x5BB7, 0x8D2E, 0x5E0CB24CEED3)
}

extension COM.COMInterop where ABIStruct == SWRT_WinRTComponent_IInt32Wrapper {
    public func get_GetSet() throws -> Swift.Int32 {
        var _result: Swift.Int32 = 0
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.get_GetSet(this, &_result))
        return _result
    }

    public func put_GetSet(_ value: Swift.Int32) throws {
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.put_GetSet(this, value))
    }

    public func get_GetOnly() throws -> Swift.Int32 {
        var _result: Swift.Int32 = 0
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.get_GetOnly(this, &_result))
        return _result
    }
}