// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public func uuidof(_: SWRT_WinRTComponent_IReturnArgumentStatics.Type) -> COM.COMInterfaceID {
    COMInterfaceID(0x4DAC0898, 0x72AE, 0x5B0D, 0x9A9E, 0x0973A5D64030)
}

extension COM.COMInterop where ABIStruct == SWRT_WinRTComponent_IReturnArgumentStatics {
    public func create() throws -> IReturnArgument? {
        var _result: Swift.UnsafeMutablePointer<SWRT_WinRTComponent_IReturnArgument>? = nil
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.Create(this, &_result))
        return IReturnArgumentBinding.fromABI(consuming: &_result)
    }

    public func createProxy(_ inner: IReturnArgument?) throws -> IReturnArgument? {
        var inner_abi = try IReturnArgumentBinding.toABI(inner)
        defer { IReturnArgumentBinding.release(&inner_abi) }
        var _result: Swift.UnsafeMutablePointer<SWRT_WinRTComponent_IReturnArgument>? = nil
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.CreateProxy(this, inner_abi, &_result))
        return IReturnArgumentBinding.fromABI(consuming: &_result)
    }
}