// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public func uuidof(_: SWRT_WinRTComponent_IObjectReferencerFactory.Type) -> COM.COMInterfaceID {
    COMInterfaceID(0x704488D8, 0xDBE4, 0x5CAB, 0xB836, 0xCDD37EB6CA5C)
}

extension COM.COMInterop where ABIStruct == SWRT_WinRTComponent_IObjectReferencerFactory {
    public func createInstance(_ obj: WindowsRuntime.IInspectable?) throws -> COM.COMReference<SWRT_WinRTComponent_IObjectReferencer> {
        var obj_abi = try WindowsRuntime.IInspectableBinding.toABI(obj)
        defer { WindowsRuntime.IInspectableBinding.release(&obj_abi) }
        var _result: Swift.UnsafeMutablePointer<SWRT_WinRTComponent_IObjectReferencer>? = nil
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.CreateInstance(this, obj_abi, &_result))
        guard let _result else { throw COMError.pointer }
        return COM.COMReference(transferringRef: _result)
    }
}