// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public func uuidof(_: SWRT_WinRTComponent_IInterfaceCastingStatics.Type) -> COM.COMInterfaceID {
    COMInterfaceID(0x4629ED8E, 0xF3EF, 0x5E3B, 0x8297, 0x9EDB823266B3)
}

extension COM.COMInterop where ABIStruct == SWRT_WinRTComponent_IInterfaceCastingStatics {
    public func asMinimalInterface(_ object: WindowsRuntime.IInspectable?) throws -> IMinimalInterface? {
        var object_abi = try WindowsRuntime.IInspectableBinding.toABI(object)
        defer { WindowsRuntime.IInspectableBinding.release(&object_abi) }
        var _result: Swift.UnsafeMutablePointer<SWRT_WinRTComponent_IMinimalInterface>? = nil
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.AsMinimalInterface(this, object_abi, &_result))
        return IMinimalInterfaceBinding.fromABI(consuming: &_result)
    }
}