// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public func uuidof(_: SWRT_WinRTComponent_IByteBuffersStatics.Type) -> COM.COMInterfaceID {
    COMInterfaceID(0x1630EBDA, 0x054E, 0x537B, 0x9079, 0x02A45A0BDD83)
}

extension COM.COMInterop where ABIStruct == SWRT_WinRTComponent_IByteBuffersStatics {
    public func memoryBufferToArray(_ buffer: WindowsFoundation_IMemoryBuffer?) throws -> [Swift.UInt8] {
        var buffer_abi = try WindowsFoundation_IMemoryBufferBinding.toABI(buffer)
        defer { WindowsFoundation_IMemoryBufferBinding.release(&buffer_abi) }
        var _result: COM.COMArray<Swift.UInt8> = .init()
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.MemoryBufferToArray(this, buffer_abi, &_result.count, &_result.pointer))
        return WindowsRuntime.ArrayBinding<WindowsRuntime.UInt8Binding>.fromABI(consuming: &_result)
    }

    public func storageBufferToArray(_ buffer: WindowsStorageStreams_IBuffer?) throws -> [Swift.UInt8] {
        var buffer_abi = try WindowsStorageStreams_IBufferBinding.toABI(buffer)
        defer { WindowsStorageStreams_IBufferBinding.release(&buffer_abi) }
        var _result: COM.COMArray<Swift.UInt8> = .init()
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.StorageBufferToArray(this, buffer_abi, &_result.count, &_result.pointer))
        return WindowsRuntime.ArrayBinding<WindowsRuntime.UInt8Binding>.fromABI(consuming: &_result)
    }

    public func arrayToMemoryBuffer(_ bytes: [Swift.UInt8]) throws -> WindowsFoundation_IMemoryBuffer? {
        var bytes_abi = try WindowsRuntime.ArrayBinding<WindowsRuntime.UInt8Binding>.toABI(bytes)
        defer { WindowsRuntime.ArrayBinding<WindowsRuntime.UInt8Binding>.release(&bytes_abi) }
        var _result: Swift.UnsafeMutablePointer<SWRT_WindowsFoundation_IMemoryBuffer>? = nil
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.ArrayToMemoryBuffer(this, bytes_abi.count, bytes_abi.pointer, &_result))
        return WindowsFoundation_IMemoryBufferBinding.fromABI(consuming: &_result)
    }

    public func arrayToStorageBuffer(_ bytes: [Swift.UInt8]) throws -> WindowsStorageStreams_IBuffer? {
        var bytes_abi = try WindowsRuntime.ArrayBinding<WindowsRuntime.UInt8Binding>.toABI(bytes)
        defer { WindowsRuntime.ArrayBinding<WindowsRuntime.UInt8Binding>.release(&bytes_abi) }
        var _result: Swift.UnsafeMutablePointer<SWRT_WindowsStorageStreams_IBuffer>? = nil
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.ArrayToStorageBuffer(this, bytes_abi.count, bytes_abi.pointer, &_result))
        return WindowsStorageStreams_IBufferBinding.fromABI(consuming: &_result)
    }
}