// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public func uuidof(_: SWRT_WinRTComponent_IObjectReferencer.Type) -> COM.COMInterfaceID {
    COMInterfaceID(0x57B25816, 0x29A4, 0x50A2, 0x9EC0, 0xE1545FA069D2)
}

extension COM.COMInterop where ABIStruct == SWRT_WinRTComponent_IObjectReferencer {
    public func get_Target() throws -> WindowsRuntime.IInspectable? {
        var _result: WindowsRuntime.IInspectablePointer? = nil
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.get_Target(this, &_result))
        return WindowsRuntime.IInspectableBinding.fromABI(consuming: &_result)
    }

    public func callAddRef() throws -> Swift.UInt32 {
        var _result: Swift.UInt32 = 0
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.CallAddRef(this, &_result))
        return _result
    }

    public func callRelease() throws -> Swift.UInt32 {
        var _result: Swift.UInt32 = 0
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.CallRelease(this, &_result))
        return _result
    }

    public func clear() throws {
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.Clear(this))
    }
}