// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public func uuidof(_: SWRT_WinRTComponent_IOverloadedSum.Type) -> COM.COMInterfaceID {
    COMInterfaceID(0x2A46C2C8, 0x63CE, 0x5A4C, 0xAE85, 0xC25658CAED5B)
}

extension COM.COMInterop where ABIStruct == SWRT_WinRTComponent_IOverloadedSum {
    public func get_Result() throws -> Swift.Int32 {
        var _result: Swift.Int32 = 0
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.get_Result(this, &_result))
        return _result
    }
}