// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public func uuidof(_: SWRT_WinRTComponent_IMinimalDerivedClassFactory.Type) -> COM.COMInterfaceID {
    COMInterfaceID(0xD52EBC83, 0x598B, 0x547A, 0x9485, 0xB2EC994430B3)
}

extension COM.COMInterop where ABIStruct == SWRT_WinRTComponent_IMinimalDerivedClassFactory {
    public func createInstance(_ baseInterface: WindowsRuntime.IInspectablePointer?, _ innerInterface: inout WindowsRuntime.IInspectablePointer?) throws -> COM.COMReference<SWRT_WinRTComponent_IMinimalDerivedClass> {
        var _result: Swift.UnsafeMutablePointer<SWRT_WinRTComponent_IMinimalDerivedClass>? = nil
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.CreateInstance(this, baseInterface, &innerInterface, &_result))
        guard let _result else { throw COMError.pointer }
        return COM.COMReference(transferringRef: _result)
    }
}