// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public func uuidof(_: SWRT_WinRTComponent_IWeakReferencer.Type) -> COM.COMInterfaceID {
    COMInterfaceID(0x236BFF57, 0x6B61, 0x5276, 0x9C1E, 0xED5A6D4A38AA)
}

extension COM.COMInterop where ABIStruct == SWRT_WinRTComponent_IWeakReferencer {
    public func get_Target() throws -> WindowsRuntime.IInspectable? {
        var _result: WindowsRuntime.IInspectablePointer? = nil
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.get_Target(this, &_result))
        return WindowsRuntime.IInspectableBinding.fromABI(consuming: &_result)
    }
}