// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public func uuidof(_: SWRT_WinRTComponent_IEventsStatics.Type) -> COM.COMInterfaceID {
    COMInterfaceID(0x57B2C647, 0x6E81, 0x50D4, 0xAA82, 0x1DC3A5665496)
}

extension COM.COMInterop where ABIStruct == SWRT_WinRTComponent_IEventsStatics {
    public func createSource() throws -> IEventSource? {
        var _result: Swift.UnsafeMutablePointer<SWRT_WinRTComponent_IEventSource>? = nil
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.CreateSource(this, &_result))
        return IEventSourceBinding.fromABI(consuming: &_result)
    }

    public func createCounter(_ source: IEventSource?) throws -> IEventCounter? {
        var source_abi = try IEventSourceBinding.toABI(source)
        defer { IEventSourceBinding.release(&source_abi) }
        var _result: Swift.UnsafeMutablePointer<SWRT_WinRTComponent_IEventCounter>? = nil
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.CreateCounter(this, source_abi, &_result))
        return IEventCounterBinding.fromABI(consuming: &_result)
    }
}