// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public func uuidof(_: SWRT_WinRTComponent_ICollectionsStatics.Type) -> COM.COMInterfaceID {
    COMInterfaceID(0x184D9228, 0x38B0, 0x5FB0, 0x8EB5, 0x08974D33C074)
}

extension COM.COMInterop where ABIStruct == SWRT_WinRTComponent_ICollectionsStatics {
    public func createIterable(_ values: [Swift.Int32]) throws -> WindowsFoundationCollections_IIterable<Swift.Int32>? {
        var values_abi = try WindowsRuntime.ArrayBinding<WindowsRuntime.Int32Binding>.toABI(values)
        defer { WindowsRuntime.ArrayBinding<WindowsRuntime.Int32Binding>.release(&values_abi) }
        var _result: Swift.UnsafeMutablePointer<SWRT_WindowsFoundationCollections_IIterable_Int32>? = nil
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.CreateIterable(this, values_abi.count, values_abi.pointer, &_result))
        return WindowsFoundationCollections_IIterableBinding.Int32.fromABI(consuming: &_result)
    }

    public func createVector(_ values: [Swift.Int32]) throws -> WindowsFoundationCollections_IVector<Swift.Int32>? {
        var values_abi = try WindowsRuntime.ArrayBinding<WindowsRuntime.Int32Binding>.toABI(values)
        defer { WindowsRuntime.ArrayBinding<WindowsRuntime.Int32Binding>.release(&values_abi) }
        var _result: Swift.UnsafeMutablePointer<SWRT_WindowsFoundationCollections_IVector_Int32>? = nil
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.CreateVector(this, values_abi.count, values_abi.pointer, &_result))
        return WindowsFoundationCollections_IVectorBinding.Int32.fromABI(consuming: &_result)
    }

    public func iterableToArray(_ iterable: WindowsFoundationCollections_IIterable<Swift.Int32>?) throws -> [Swift.Int32] {
        var iterable_abi = try WindowsFoundationCollections_IIterableBinding.Int32.toABI(iterable)
        defer { WindowsFoundationCollections_IIterableBinding.Int32.release(&iterable_abi) }
        var _result: COM.COMArray<Swift.Int32> = .init()
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.IterableToArray(this, iterable_abi, &_result.count, &_result.pointer))
        return WindowsRuntime.ArrayBinding<WindowsRuntime.Int32Binding>.fromABI(consuming: &_result)
    }
}