// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public func uuidof(_: SWRT_WinRTComponent_IOverloadedSumFactory.Type) -> COM.COMInterfaceID {
    COMInterfaceID(0x29E8C1A7, 0xF68E, 0x5AC1, 0xA208, 0x303F24F58F32)
}

extension COM.COMInterop where ABIStruct == SWRT_WinRTComponent_IOverloadedSumFactory {
    public func createInstance(_ a: Swift.Int32) throws -> COM.COMReference<SWRT_WinRTComponent_IOverloadedSum> {
        var _result: Swift.UnsafeMutablePointer<SWRT_WinRTComponent_IOverloadedSum>? = nil
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.CreateInstance(this, a, &_result))
        guard let _result else { throw COMError.pointer }
        return COM.COMReference(transferringRef: _result)
    }

    public func createInstance2(_ a: Swift.Int32, _ b: Swift.Int32) throws -> COM.COMReference<SWRT_WinRTComponent_IOverloadedSum> {
        var _result: Swift.UnsafeMutablePointer<SWRT_WinRTComponent_IOverloadedSum>? = nil
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.CreateInstance2(this, a, b, &_result))
        guard let _result else { throw COMError.pointer }
        return COM.COMReference(transferringRef: _result)
    }
}