// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public func uuidof(_: SWRT_WinRTComponent_IMinimalBaseClass.Type) -> COM.COMInterfaceID {
    COMInterfaceID(0xB1E19344, 0x7063, 0x5C60, 0x9940, 0x30DCE4001483)
}

extension COM.COMInterop where ABIStruct == SWRT_WinRTComponent_IMinimalBaseClass {
}