// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public func uuidof(_: SWRT_WinRTComponent_ISwiftAttributesStatics.Type) -> COM.COMInterfaceID {
    COMInterfaceID(0x1B79AE00, 0x0CC0, 0x56A1, 0xA00F, 0x34D37175E365)
}

extension COM.COMInterop where ABIStruct == SWRT_WinRTComponent_ISwiftAttributesStatics {
    public func mainActor() throws {
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.MainActor(this))
    }

    public func availableFromSwift1() throws {
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.AvailableFromSwift1(this))
    }

    public func availableFromSwift1WithDiscardableResult() throws -> Swift.Int32 {
        var _result: Swift.Int32 = 0
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.AvailableFromSwift1WithDiscardableResult(this, &_result))
        return _result
    }
}