// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public func uuidof(_: SWRT_WinRTComponent_IMinimalDerivedClass.Type) -> COM.COMInterfaceID {
    COMInterfaceID(0x437EBA1E, 0xE45A, 0x5DCB, 0xBF44, 0xE69220C13941)
}

extension COM.COMInterop where ABIStruct == SWRT_WinRTComponent_IMinimalDerivedClass {
}