// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public func uuidof(_: SWRT_WinRTComponent_IWeakReferencerFactory.Type) -> COM.COMInterfaceID {
    COMInterfaceID(0x4307AF14, 0xC00A, 0x523F, 0xB9C5, 0x00F0BAD7EC3D)
}

extension COM.COMInterop where ABIStruct == SWRT_WinRTComponent_IWeakReferencerFactory {
    public func createInstance(_ target: WindowsRuntime.IInspectable?) throws -> COM.COMReference<SWRT_WinRTComponent_IWeakReferencer> {
        var target_abi = try WindowsRuntime.IInspectableBinding.toABI(target)
        defer { WindowsRuntime.IInspectableBinding.release(&target_abi) }
        var _result: Swift.UnsafeMutablePointer<SWRT_WinRTComponent_IWeakReferencer>? = nil
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.CreateInstance(this, target_abi, &_result))
        guard let _result else { throw COMError.pointer }
        return COM.COMReference(transferringRef: _result)
    }
}