// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public func uuidof(_: SWRT_WinRTComponent_IEventCounter.Type) -> COM.COMInterfaceID {
    COMInterfaceID(0xE02202D2, 0xEDE9, 0x5020, 0xA3D4, 0xB6BD22E00FAC)
}

extension COM.COMInterop where ABIStruct == SWRT_WinRTComponent_IEventCounter {
    public func get_Count() throws -> Swift.Int32 {
        var _result: Swift.Int32 = 0
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.get_Count(this, &_result))
        return _result
    }

    public func detach() throws {
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.Detach(this))
    }
}