// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public func uuidof(_: SWRT_WinRTComponent_IMinimalInterface.Type) -> COM.COMInterfaceID {
    COMInterfaceID(0xA1636347, 0x43AD, 0x5823, 0xBAFB, 0x500722544596)
}

extension COM.COMInterop where ABIStruct == SWRT_WinRTComponent_IMinimalInterface {
    public func method() throws {
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.Method(this))
    }
}