// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public func uuidof(_: SWRT_WinRTComponent_IMinimalDerivedClassStatics.Type) -> COM.COMInterfaceID {
    COMInterfaceID(0xC2996F9C, 0xAFAC, 0x546E, 0x8131, 0x288AFCE5B880)
}

extension COM.COMInterop where ABIStruct == SWRT_WinRTComponent_IMinimalDerivedClassStatics {
    public func createDerived() throws -> MinimalDerivedClass? {
        var _result: Swift.UnsafeMutablePointer<SWRT_WinRTComponent_IMinimalDerivedClass>? = nil
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.CreateDerived(this, &_result))
        return MinimalDerivedClassBinding.fromABI(consuming: &_result)
    }
}