// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

internal func uuidof(_: SWRT_WindowsFoundation_IAsyncOperation_Int32.Type) -> COM.COMInterfaceID {
    COMInterfaceID(0x968B9665, 0x06ED, 0x5774, 0x8F53, 0x8EDEABD5F7B5)
}

extension COM.COMInterop where ABIStruct == SWRT_WindowsFoundation_IAsyncOperation_Int32 {
    internal func put_Completed(_ handler: WindowsFoundation_AsyncOperationCompletedHandler<Swift.Int32>?) throws {
        var handler_abi = try WindowsFoundation_AsyncOperationCompletedHandlerBinding.Int32.toABI(handler)
        defer { WindowsFoundation_AsyncOperationCompletedHandlerBinding.Int32.release(&handler_abi) }
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.put_Completed(this, handler_abi))
    }

    internal func get_Completed() throws -> WindowsFoundation_AsyncOperationCompletedHandler<Swift.Int32>? {
        var _result: Swift.UnsafeMutablePointer<SWRT_WindowsFoundation_AsyncOperationCompletedHandler_Int32>? = nil
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.get_Completed(this, &_result))
        return WindowsFoundation_AsyncOperationCompletedHandlerBinding.Int32.fromABI(consuming: &_result)
    }

    internal func getResults() throws -> Swift.Int32 {
        var _result: Swift.Int32 = 0
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.GetResults(this, &_result))
        return _result
    }
}