// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

internal func uuidof(_: SWRT_WindowsFoundation_AsyncOperationCompletedHandler_Int32.Type) -> COM.COMInterfaceID {
    COMInterfaceID(0xD60CAE9D, 0x88CB, 0x59F1, 0x8576, 0x3FBA44796BE8)
}

extension COM.COMInterop where ABIStruct == SWRT_WindowsFoundation_AsyncOperationCompletedHandler_Int32 {
    internal func invoke(_ asyncInfo: WindowsFoundation_IAsyncOperation<Swift.Int32>?, _ asyncStatus: WindowsFoundation_AsyncStatus) throws {
        var asyncInfo_abi = try WindowsFoundation_IAsyncOperationBinding.Int32.toABI(asyncInfo)
        defer { WindowsFoundation_IAsyncOperationBinding.Int32.release(&asyncInfo_abi) }
        let asyncStatus_abi = WindowsFoundation_AsyncStatus.toABI(asyncStatus)
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.Invoke(this, asyncInfo_abi, asyncStatus_abi))
    }
}