// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import UWP_ABI

public func uuidof(_: SWRT_WindowsStorageStreams_IBuffer.Type) -> COM.COMInterfaceID {
    COMInterfaceID(0x905A0FE0, 0xBC53, 0x11DF, 0x8C49, 0x001E4FC686DA)
}

extension COM.COMInterop where ABIStruct == SWRT_WindowsStorageStreams_IBuffer {
    public func get_Capacity() throws -> Swift.UInt32 {
        var _result: Swift.UInt32 = 0
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.get_Capacity(this, &_result))
        return _result
    }

    public func get_Length() throws -> Swift.UInt32 {
        var _result: Swift.UInt32 = 0
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.get_Length(this, &_result))
        return _result
    }

    public func put_Length(_ value: Swift.UInt32) throws {
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.put_Length(this, value))
    }
}