// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import UWP_ABI

public func uuidof(_: SWRT_WindowsStorageStreams_IBufferStatics.Type) -> COM.COMInterfaceID {
    COMInterfaceID(0xE901E65B, 0xD716, 0x475A, 0xA90A, 0xAF7229B1E741)
}

extension COM.COMInterop where ABIStruct == SWRT_WindowsStorageStreams_IBufferStatics {
    public func createCopyFromMemoryBuffer(_ input: WindowsFoundation_IMemoryBuffer?) throws -> WindowsStorageStreams_Buffer? {
        var input_abi = try WindowsFoundation_IMemoryBufferBinding.toABI(input)
        defer { WindowsFoundation_IMemoryBufferBinding.release(&input_abi) }
        var _result: Swift.UnsafeMutablePointer<SWRT_WindowsStorageStreams_IBuffer>? = nil
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.CreateCopyFromMemoryBuffer(this, input_abi, &_result))
        return WindowsStorageStreams_BufferBinding.fromABI(consuming: &_result)
    }

    public func createMemoryBufferOverIBuffer(_ input: WindowsStorageStreams_IBuffer?) throws -> WindowsFoundation_MemoryBuffer? {
        var input_abi = try WindowsStorageStreams_IBufferBinding.toABI(input)
        defer { WindowsStorageStreams_IBufferBinding.release(&input_abi) }
        var _result: Swift.UnsafeMutablePointer<SWRT_WindowsFoundation_IMemoryBuffer>? = nil
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.CreateMemoryBufferOverIBuffer(this, input_abi, &_result))
        return WindowsFoundation_MemoryBufferBinding.fromABI(consuming: &_result)
    }
}