// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import UWP_ABI

/// Represents an asynchronous operation, which returns a result upon completion. This is the return type for many Windows Runtime asynchronous methods that have results but don't report progress.
public typealias WindowsFoundation_IAsyncOperation<TResult> = any WindowsFoundation_IAsyncOperationProtocol<TResult>

/// Represents an asynchronous operation, which returns a result upon completion. This is the return type for many Windows Runtime asynchronous methods that have results but don't report progress.
public protocol WindowsFoundation_IAsyncOperationProtocol<TResult>: WindowsFoundation_IAsyncInfoProtocol {
    associatedtype TResult

    /// Returns the results of the operation.
    /// - Returns: The results of the operation.
    func getResults() throws -> TResult

    /// Gets or sets the method that handles the operation completed notification.
    /// - Returns: The method that handles the notification.
    func _completed() throws -> WindowsFoundation_AsyncOperationCompletedHandler<TResult>

    func _completed(_ handler: WindowsFoundation_AsyncOperationCompletedHandler<TResult>?) throws
}

extension WindowsFoundation_IAsyncOperationProtocol {
    /// Gets or sets the method that handles the operation completed notification.
    /// - Returns: The method that handles the notification.
    public var completed: WindowsFoundation_AsyncOperationCompletedHandler<TResult>! {
        get {
            try! NullResult.catch(self._completed())
        }
        set {
            try! self._completed(newValue)
        }
    }
}