// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import UWP_ABI

/// Represents a reference to an IMemoryBuffer object.
public typealias WindowsFoundation_IMemoryBufferReference = any WindowsFoundation_IMemoryBufferReferenceProtocol

/// Represents a reference to an IMemoryBuffer object.
public protocol WindowsFoundation_IMemoryBufferReferenceProtocol: WindowsFoundation_IClosableProtocol {
    /// Occurs when MemoryBuffer.Close has been called, but before this IMemoryBufferReference has been closed.
    func closed(adding handler: WindowsFoundation_TypedEventHandler<WindowsFoundation_IMemoryBufferReference?, WindowsRuntime.IInspectable?>?) throws -> WindowsRuntime.EventRegistration
    func closed(removing cookie: WindowsRuntime.EventRegistrationToken) throws

    /// Gets the size of the memory buffer in bytes.
    /// - Returns: The size of the memory buffer in bytes.
    func _capacity() throws -> Swift.UInt32
}

extension WindowsFoundation_IMemoryBufferReferenceProtocol {
    /// Gets the size of the memory buffer in bytes.
    /// - Returns: The size of the memory buffer in bytes.
    public var capacity: Swift.UInt32 {
        try! self._capacity()
    }
}