// Generated by swift-winrt
// swiftlint:disable all

import UWP

public typealias AsyncOperationCompletedHandler<TResult> = WindowsFoundation_AsyncOperationCompletedHandler<TResult>
public typealias AsyncOperationCompletedHandlerBinding = WindowsFoundation_AsyncOperationCompletedHandlerBinding
public typealias AsyncStatus = WindowsFoundation_AsyncStatus
public typealias DateTime = WindowsFoundation_DateTime
public typealias IAsyncInfo = WindowsFoundation_IAsyncInfo

public protocol IAsyncInfoProtocol: WindowsFoundation_IAsyncInfoProtocol {
}

public typealias IAsyncInfoBinding = WindowsFoundation_IAsyncInfoBinding
public typealias IAsyncOperation<TResult> = WindowsFoundation_IAsyncOperation<TResult>

public protocol IAsyncOperationProtocol<TResult>: WindowsFoundation_IAsyncOperationProtocol {
}

public typealias IAsyncOperationBinding = WindowsFoundation_IAsyncOperationBinding
public typealias IClosable = WindowsFoundation_IClosable

public protocol IClosableProtocol: WindowsFoundation_IClosableProtocol {
}

public typealias IClosableBinding = WindowsFoundation_IClosableBinding
public typealias IMemoryBuffer = WindowsFoundation_IMemoryBuffer

public protocol IMemoryBufferProtocol: WindowsFoundation_IMemoryBufferProtocol {
}

public typealias IMemoryBufferBinding = WindowsFoundation_IMemoryBufferBinding
public typealias IMemoryBufferReference = WindowsFoundation_IMemoryBufferReference

public protocol IMemoryBufferReferenceProtocol: WindowsFoundation_IMemoryBufferReferenceProtocol {
}

public typealias IMemoryBufferReferenceBinding = WindowsFoundation_IMemoryBufferReferenceBinding
public typealias IPropertyValue = WindowsFoundation_IPropertyValue

public protocol IPropertyValueProtocol: WindowsFoundation_IPropertyValueProtocol {
}

public typealias IPropertyValueBinding = WindowsFoundation_IPropertyValueBinding
public typealias IReference<T> = WindowsFoundation_IReference<T>

public protocol IReferenceProtocol<T>: WindowsFoundation_IReferenceProtocol {
}

public typealias IReferenceBinding = WindowsFoundation_IReferenceBinding
public typealias MemoryBuffer = WindowsFoundation_MemoryBuffer
public typealias Point = WindowsFoundation_Point
public typealias PropertyType = WindowsFoundation_PropertyType
public typealias Rect = WindowsFoundation_Rect
public typealias Size = WindowsFoundation_Size
public typealias TimeSpan = WindowsFoundation_TimeSpan
public typealias TypedEventHandler<TSender, TResult> = WindowsFoundation_TypedEventHandler<TSender, TResult>
public typealias TypedEventHandlerBinding = WindowsFoundation_TypedEventHandlerBinding