// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

// MARK: Windows.Foundation.Collections.IIterable`1<Int32>

extension WindowsFoundationCollections_IIterableBinding {
    internal enum Int32: WindowsRuntime.InterfaceBinding {
        public typealias SwiftObject = WindowsFoundationCollections_IIterable<Swift.Int32>
        public typealias ABIStruct = SWRT_WindowsFoundationCollections_IIterable_Int32

        public static let typeName = "Windows.Foundation.Collections.IIterable`1<Int32>"

        public static var interfaceID: COM.COMInterfaceID {
            uuidof(ABIStruct.self)
        }

        public static func _wrap(_ reference: consuming ABIReference) -> SwiftObject {
            Import(_wrapping: consume reference)
        }

        private final class Import: WinRTImport<Int32>, WindowsFoundationCollections_IIterableProtocol {
            public func first() throws -> WindowsFoundationCollections_IIterator<Swift.Int32> {
                try COM.NullResult.unwrap(_interop.first())
            }
        }

        public static var virtualTablePointer: UnsafeRawPointer {
            .init(withUnsafePointer(to: &virtualTable) { $0 })
        }

        private static var virtualTable = SWRT_WindowsFoundationCollections_IIterable_Int32_VirtualTable(
            QueryInterface: { IUnknownVirtualTable.QueryInterface($0, $1, $2) },
            AddRef: { IUnknownVirtualTable.AddRef($0) },
            Release: { IUnknownVirtualTable.Release($0) },
            GetIids: { IInspectableVirtualTable.GetIids($0, $1, $2) },
            GetRuntimeClassName: { IInspectableVirtualTable.GetRuntimeClassName($0, $1) },
            GetTrustLevel: { IInspectableVirtualTable.GetTrustLevel($0, $1) },
            First: { this, _result in _implement(this) { this in
                guard let _result else { throw COM.COMError.pointer }
                let _result_swift = try COM.NullResult.`catch`(try this.first())
                _result.pointee = try WindowsFoundationCollections_IIteratorBinding.Int32.toABI(_result_swift)
            } }
        )
    }
}