// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

// MARK: Windows.Foundation.Collections.IVector`1<Int32>

extension WindowsFoundationCollections_IVectorBinding {
    internal enum Int32: WindowsRuntime.InterfaceBinding {
        public typealias SwiftObject = WindowsFoundationCollections_IVector<Swift.Int32>
        public typealias ABIStruct = SWRT_WindowsFoundationCollections_IVector_Int32

        public static let typeName = "Windows.Foundation.Collections.IVector`1<Int32>"

        public static var interfaceID: COM.COMInterfaceID {
            uuidof(ABIStruct.self)
        }

        public static func _wrap(_ reference: consuming ABIReference) -> SwiftObject {
            Import(_wrapping: consume reference)
        }

        private final class Import: WinRTImport<Int32>, WindowsFoundationCollections_IVectorProtocol {
            public typealias T = Swift.Int32

            public func getAt(_ index: Swift.UInt32) throws -> Swift.Int32 {
                try _interop.getAt(index)
            }

            public func getView() throws -> WindowsFoundationCollections_IVectorView<Swift.Int32> {
                try COM.NullResult.unwrap(_interop.getView())
            }

            public func indexOf(_ value: Swift.Int32, _ index: inout Swift.UInt32) throws -> Swift.Bool {
                try _interop.indexOf(value, &index)
            }

            public func setAt(_ index: Swift.UInt32, _ value: Swift.Int32) throws {
                try _interop.setAt(index, value)
            }

            public func insertAt(_ index: Swift.UInt32, _ value: Swift.Int32) throws {
                try _interop.insertAt(index, value)
            }

            public func removeAt(_ index: Swift.UInt32) throws {
                try _interop.removeAt(index)
            }

            public func append(_ value: Swift.Int32) throws {
                try _interop.append(value)
            }

            public func removeAtEnd() throws {
                try _interop.removeAtEnd()
            }

            public func clear() throws {
                try _interop.clear()
            }

            public func getMany(_ startIndex: Swift.UInt32, _ items: [Swift.Int32]) throws -> Swift.UInt32 {
                try _interop.getMany(startIndex, items)
            }

            public func replaceAll(_ items: [Swift.Int32]) throws {
                try _interop.replaceAll(items)
            }

            public func _size() throws -> Swift.UInt32 {
                try _interop.get_Size()
            }

            // MARK: Windows.Foundation.Collections.IIterable`1<Int32> members

            public func first() throws -> WindowsFoundationCollections_IIterator<Swift.Int32> {
                try COM.NullResult.unwrap(_iiterable.first())
            }

            private var _lazyIIterable: COM.COMReference<SWRT_WindowsFoundationCollections_IIterable_Int32>.Optional = .none

            internal var _iiterable: COM.COMInterop<SWRT_WindowsFoundationCollections_IIterable_Int32> {
                get throws {
                    try _lazyIIterable.lazyInitInterop {
                        try _queryInterface(uuidof(SWRT_WindowsFoundationCollections_IIterable_Int32.self)).cast()
                    }
                }
            }
        }

        public static var virtualTablePointer: UnsafeRawPointer {
            .init(withUnsafePointer(to: &virtualTable) { $0 })
        }

        private static var virtualTable = SWRT_WindowsFoundationCollections_IVector_Int32_VirtualTable(
            QueryInterface: { IUnknownVirtualTable.QueryInterface($0, $1, $2) },
            AddRef: { IUnknownVirtualTable.AddRef($0) },
            Release: { IUnknownVirtualTable.Release($0) },
            GetIids: { IInspectableVirtualTable.GetIids($0, $1, $2) },
            GetRuntimeClassName: { IInspectableVirtualTable.GetRuntimeClassName($0, $1) },
            GetTrustLevel: { IInspectableVirtualTable.GetTrustLevel($0, $1) },
            GetAt: { this, index, _result in _implement(this) { this in
                guard let _result else { throw COM.COMError.pointer }
                _result.pointee = try this.getAt(index)
            } },
            get_Size: { this, _result in _implement(this) { this in
                guard let _result else { throw COM.COMError.pointer }
                _result.pointee = try this._size()
            } },
            GetView: { this, _result in _implement(this) { this in
                guard let _result else { throw COM.COMError.pointer }
                let _result_swift = try COM.NullResult.`catch`(try this.getView())
                _result.pointee = try WindowsFoundationCollections_IVectorViewBinding.Int32.toABI(_result_swift)
            } },
            IndexOf: { this, value, index, _result in _implement(this) { this in
                guard let index else { throw COM.COMError.pointer }
                guard let _result else { throw COM.COMError.pointer }
                _result.pointee = try this.indexOf(value, &index.pointee)
            } },
            SetAt: { this, index, value in _implement(this) { this in
                try this.setAt(index, value)
            } },
            InsertAt: { this, index, value in _implement(this) { this in
                try this.insertAt(index, value)
            } },
            RemoveAt: { this, index in _implement(this) { this in
                try this.removeAt(index)
            } },
            Append: { this, value in _implement(this) { this in
                try this.append(value)
            } },
            RemoveAtEnd: { this in _implement(this) { this in
                try this.removeAtEnd()
            } },
            Clear: { this in _implement(this) { this in
                try this.clear()
            } },
            GetMany: { this, startIndex, itemsLength, items, _result in _implement(this) { this in
                guard let _result else { throw COM.COMError.pointer }
                let items_swift = WindowsRuntime.ArrayBinding<WindowsRuntime.Int32Binding>.fromABI(pointer: items, count: itemsLength)
                _result.pointee = try this.getMany(startIndex, items_swift)
            } },
            ReplaceAll: { this, itemsLength, items in _implement(this) { this in
                let items_swift = WindowsRuntime.ArrayBinding<WindowsRuntime.Int32Binding>.fromABI(pointer: items, count: itemsLength)
                try this.replaceAll(items_swift)
            } }
        )
    }
}