// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import UWP_ABI

internal func uuidof(_: SWRT_WindowsFoundation_TypedEventHandler_WindowsFoundation_IMemoryBufferReference_IInspectable.Type) -> COM.COMInterfaceID {
    COMInterfaceID(0xF4637D4A, 0x0760, 0x5431, 0xBFC0, 0x24EB1D4F6C4F)
}

extension COM.COMInterop where ABIStruct == SWRT_WindowsFoundation_TypedEventHandler_WindowsFoundation_IMemoryBufferReference_IInspectable {
    internal func invoke(_ sender: WindowsFoundation_IMemoryBufferReference?, _ args: WindowsRuntime.IInspectable?) throws {
        var sender_abi = try WindowsFoundation_IMemoryBufferReferenceBinding.toABI(sender)
        defer { WindowsFoundation_IMemoryBufferReferenceBinding.release(&sender_abi) }
        var args_abi = try WindowsRuntime.IInspectableBinding.toABI(args)
        defer { WindowsRuntime.IInspectableBinding.release(&args_abi) }
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.Invoke(this, sender_abi, args_abi))
    }
}