// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import UWP_ABI

public func uuidof(_: SWRT_WindowsFoundation_IClosable.Type) -> COM.COMInterfaceID {
    COMInterfaceID(0x30D5A829, 0x7FA4, 0x4026, 0x83BB, 0xD75BAE4EA99E)
}

extension COM.COMInterop where ABIStruct == SWRT_WindowsFoundation_IClosable {
    public func close() throws {
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.Close(this))
    }
}