// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import UWP_ABI

public func uuidof(_: SWRT_WindowsFoundation_IMemoryBuffer.Type) -> COM.COMInterfaceID {
    COMInterfaceID(0xFBC4DD2A, 0x245B, 0x11E4, 0xAF98, 0x689423260CF8)
}

extension COM.COMInterop where ABIStruct == SWRT_WindowsFoundation_IMemoryBuffer {
    public func createReference() throws -> WindowsFoundation_IMemoryBufferReference? {
        var _result: Swift.UnsafeMutablePointer<SWRT_WindowsFoundation_IMemoryBufferReference>? = nil
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.CreateReference(this, &_result))
        return WindowsFoundation_IMemoryBufferReferenceBinding.fromABI(consuming: &_result)
    }
}