// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import UWP_ABI

public func uuidof(_: SWRT_WindowsFoundation_IMemoryBufferReference.Type) -> COM.COMInterfaceID {
    COMInterfaceID(0xFBC4DD29, 0x245B, 0x11E4, 0xAF98, 0x689423260CF8)
}

extension COM.COMInterop where ABIStruct == SWRT_WindowsFoundation_IMemoryBufferReference {
    public func get_Capacity() throws -> Swift.UInt32 {
        var _result: Swift.UInt32 = 0
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.get_Capacity(this, &_result))
        return _result
    }

    public func add_Closed(_ handler: WindowsFoundation_TypedEventHandler<WindowsFoundation_IMemoryBufferReference?, WindowsRuntime.IInspectable?>?) throws -> WindowsRuntime.EventRegistrationToken {
        var handler_abi = try WindowsFoundation_TypedEventHandlerBinding.IMemoryBufferReference_Object.toABI(handler)
        defer { WindowsFoundation_TypedEventHandlerBinding.IMemoryBufferReference_Object.release(&handler_abi) }
        var _result: SWRT_EventRegistrationToken = .init()
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.add_Closed(this, handler_abi, &_result))
        return WindowsRuntime.EventRegistrationToken.fromABI(_result)
    }

    public func remove_Closed(_ cookie: WindowsRuntime.EventRegistrationToken) throws {
        let cookie_abi = WindowsRuntime.EventRegistrationToken.toABI(cookie)
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.remove_Closed(this, cookie_abi))
    }
}