// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import UWP_ABI

public func uuidof(_: SWRT_WindowsFoundation_IAsyncInfo.Type) -> COM.COMInterfaceID {
    COMInterfaceID(0x00000036, 0x0000, 0x0000, 0xC000, 0x000000000046)
}

extension COM.COMInterop where ABIStruct == SWRT_WindowsFoundation_IAsyncInfo {
    public func get_Id() throws -> Swift.UInt32 {
        var _result: Swift.UInt32 = 0
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.get_Id(this, &_result))
        return _result
    }

    public func get_Status() throws -> WindowsFoundation_AsyncStatus {
        var _result: SWRT_WindowsFoundation_AsyncStatus = .init()
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.get_Status(this, &_result))
        return WindowsFoundation_AsyncStatus.fromABI(_result)
    }

    public func get_ErrorCode() throws -> COM.HResult {
        var _result: SWRT_HResult = 0
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.get_ErrorCode(this, &_result))
        return COM.HResultBinding.fromABI(_result)
    }

    public func cancel() throws {
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.Cancel(this))
    }

    public func close() throws {
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.Close(this))
    }
}