// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import UWP_ABI

public func uuidof(_: SWRT_WindowsFoundation_IMemoryBufferFactory.Type) -> COM.COMInterfaceID {
    COMInterfaceID(0xFBC4DD2B, 0x245B, 0x11E4, 0xAF98, 0x689423260CF8)
}

extension COM.COMInterop where ABIStruct == SWRT_WindowsFoundation_IMemoryBufferFactory {
    public func create(_ capacity: Swift.UInt32) throws -> COM.COMReference<SWRT_WindowsFoundation_IMemoryBuffer> {
        var _result: Swift.UnsafeMutablePointer<SWRT_WindowsFoundation_IMemoryBuffer>? = nil
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.Create(this, capacity, &_result))
        guard let _result else { throw COMError.pointer }
        return COM.COMReference(transferringRef: _result)
    }
}