// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import UWP_ABI

public class WindowsFoundation_MemoryBufferBinding: WindowsRuntime.ActivatableClassBinding {
    public typealias SwiftObject = WindowsFoundation_MemoryBuffer
    public typealias ABIStruct = SWRT_WindowsFoundation_IMemoryBuffer

    public static let typeName = "Windows.Foundation.MemoryBuffer"

    public static var interfaceID: COM.COMInterfaceID {
        uuidof(ABIStruct.self)
    }

    public static func _wrap(_ reference: consuming ABIReference) -> SwiftObject {
        WindowsFoundation_MemoryBuffer(_wrapping: consume reference)
    }
}