// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

internal func uuidof(_: SWRT_WindowsFoundationCollections_IIterable_Int32.Type) -> COM.COMInterfaceID {
    COMInterfaceID(0x81A643FB, 0xF51C, 0x5565, 0x83C4, 0xF96425777B66)
}

extension COM.COMInterop where ABIStruct == SWRT_WindowsFoundationCollections_IIterable_Int32 {
    internal func first() throws -> WindowsFoundationCollections_IIterator<Swift.Int32>? {
        var _result: Swift.UnsafeMutablePointer<SWRT_WindowsFoundationCollections_IIterator_Int32>? = nil
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.First(this, &_result))
        return WindowsFoundationCollections_IIteratorBinding.Int32.fromABI(consuming: &_result)
    }
}