// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

internal func uuidof(_: SWRT_WindowsFoundationCollections_IIterator_Int32.Type) -> COM.COMInterfaceID {
    COMInterfaceID(0xBFEA7F78, 0x50C2, 0x5F1D, 0xA6EA, 0x9E978D2699FF)
}

extension COM.COMInterop where ABIStruct == SWRT_WindowsFoundationCollections_IIterator_Int32 {
    internal func get_Current() throws -> Swift.Int32 {
        var _result: Swift.Int32 = 0
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.get_Current(this, &_result))
        return _result
    }

    internal func get_HasCurrent() throws -> Swift.Bool {
        var _result: Swift.Bool = false
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.get_HasCurrent(this, &_result))
        return _result
    }

    internal func moveNext() throws -> Swift.Bool {
        var _result: Swift.Bool = false
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.MoveNext(this, &_result))
        return _result
    }

    internal func getMany(_ items: [Swift.Int32]) throws -> Swift.UInt32 {
        var items_abi = try WindowsRuntime.ArrayBinding<WindowsRuntime.Int32Binding>.toABI(items)
        defer { WindowsRuntime.ArrayBinding<WindowsRuntime.Int32Binding>.release(&items_abi) }
        var _result: Swift.UInt32 = 0
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.GetMany(this, items_abi.count, items_abi.pointer, &_result))
        return _result
    }
}