// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

internal func uuidof(_: SWRT_WindowsFoundationCollections_IVector_Int32.Type) -> COM.COMInterfaceID {
    COMInterfaceID(0xB939AF5B, 0xB45D, 0x5489, 0x9149, 0x61442C1905FE)
}

extension COM.COMInterop where ABIStruct == SWRT_WindowsFoundationCollections_IVector_Int32 {
    internal func getAt(_ index: Swift.UInt32) throws -> Swift.Int32 {
        var _result: Swift.Int32 = 0
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.GetAt(this, index, &_result))
        return _result
    }

    internal func get_Size() throws -> Swift.UInt32 {
        var _result: Swift.UInt32 = 0
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.get_Size(this, &_result))
        return _result
    }

    internal func getView() throws -> WindowsFoundationCollections_IVectorView<Swift.Int32>? {
        var _result: Swift.UnsafeMutablePointer<SWRT_WindowsFoundationCollections_IVectorView_Int32>? = nil
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.GetView(this, &_result))
        return WindowsFoundationCollections_IVectorViewBinding.Int32.fromABI(consuming: &_result)
    }

    internal func indexOf(_ value: Swift.Int32, _ index: inout Swift.UInt32) throws -> Swift.Bool {
        var _result: Swift.Bool = false
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.IndexOf(this, value, &index, &_result))
        return _result
    }

    internal func setAt(_ index: Swift.UInt32, _ value: Swift.Int32) throws {
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.SetAt(this, index, value))
    }

    internal func insertAt(_ index: Swift.UInt32, _ value: Swift.Int32) throws {
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.InsertAt(this, index, value))
    }

    internal func removeAt(_ index: Swift.UInt32) throws {
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.RemoveAt(this, index))
    }

    internal func append(_ value: Swift.Int32) throws {
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.Append(this, value))
    }

    internal func removeAtEnd() throws {
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.RemoveAtEnd(this))
    }

    internal func clear() throws {
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.Clear(this))
    }

    internal func getMany(_ startIndex: Swift.UInt32, _ items: [Swift.Int32]) throws -> Swift.UInt32 {
        var items_abi = try WindowsRuntime.ArrayBinding<WindowsRuntime.Int32Binding>.toABI(items)
        defer { WindowsRuntime.ArrayBinding<WindowsRuntime.Int32Binding>.release(&items_abi) }
        var _result: Swift.UInt32 = 0
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.GetMany(this, startIndex, items_abi.count, items_abi.pointer, &_result))
        return _result
    }

    internal func replaceAll(_ items: [Swift.Int32]) throws {
        var items_abi = try WindowsRuntime.ArrayBinding<WindowsRuntime.Int32Binding>.toABI(items)
        defer { WindowsRuntime.ArrayBinding<WindowsRuntime.Int32Binding>.release(&items_abi) }
        try WinRTError.fromABI(this.pointee.VirtualTable.pointee.ReplaceAll(this, items_abi.count, items_abi.pointer))
    }
}