// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public enum ByteBuffers {
    // MARK: WinRTComponent.IByteBuffersStatics members

    public static func memoryBufferToArray(_ buffer: WindowsFoundation_IMemoryBuffer?) throws -> [Swift.UInt8] {
        try _ibyteBuffersStatics.memoryBufferToArray(buffer)
    }

    public static func storageBufferToArray(_ buffer: WindowsStorageStreams_IBuffer?) throws -> [Swift.UInt8] {
        try _ibyteBuffersStatics.storageBufferToArray(buffer)
    }

    public static func arrayToMemoryBuffer(_ bytes: [Swift.UInt8]) throws -> WindowsFoundation_IMemoryBuffer {
        try COM.NullResult.unwrap(_ibyteBuffersStatics.arrayToMemoryBuffer(bytes))
    }

    public static func arrayToStorageBuffer(_ bytes: [Swift.UInt8]) throws -> WindowsStorageStreams_IBuffer {
        try COM.NullResult.unwrap(_ibyteBuffersStatics.arrayToStorageBuffer(bytes))
    }

    // MARK: Implementation details

    private static var _lazyIActivationFactory: COM.COMReference<SWRT_IActivationFactory>.Optional = .init()

    private static var _iactivationFactory: COM.COMInterop<SWRT_IActivationFactory> {
        get throws {
            try _lazyIActivationFactory.lazyInitInterop {
                try WindowsRuntime.activationFactoryResolver.resolve(runtimeClass: "WinRTComponent.ByteBuffers")
            }
        }
    }

    private static var _lazyIByteBuffersStatics: COM.COMReference<SWRT_WinRTComponent_IByteBuffersStatics>.Optional = .none

    internal static var _ibyteBuffersStatics: COM.COMInterop<SWRT_WinRTComponent_IByteBuffersStatics> {
        get throws {
            try _lazyIByteBuffersStatics.lazyInitInterop {
                try _iactivationFactory.queryInterface(uuidof(SWRT_WinRTComponent_IByteBuffersStatics.self)).cast()
            }
        }
    }
}