// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public enum Collections {
    // MARK: WinRTComponent.ICollectionsStatics members

    public static func createIterable(_ values: [Swift.Int32]) throws -> WindowsFoundationCollections_IIterable<Swift.Int32> {
        try COM.NullResult.unwrap(_icollectionsStatics.createIterable(values))
    }

    public static func createVector(_ values: [Swift.Int32]) throws -> WindowsFoundationCollections_IVector<Swift.Int32> {
        try COM.NullResult.unwrap(_icollectionsStatics.createVector(values))
    }

    public static func iterableToArray(_ iterable: WindowsFoundationCollections_IIterable<Swift.Int32>?) throws -> [Swift.Int32] {
        try _icollectionsStatics.iterableToArray(iterable)
    }

    // MARK: Implementation details

    private static var _lazyIActivationFactory: COM.COMReference<SWRT_IActivationFactory>.Optional = .init()

    private static var _iactivationFactory: COM.COMInterop<SWRT_IActivationFactory> {
        get throws {
            try _lazyIActivationFactory.lazyInitInterop {
                try WindowsRuntime.activationFactoryResolver.resolve(runtimeClass: "WinRTComponent.Collections")
            }
        }
    }

    private static var _lazyICollectionsStatics: COM.COMReference<SWRT_WinRTComponent_ICollectionsStatics>.Optional = .none

    internal static var _icollectionsStatics: COM.COMInterop<SWRT_WinRTComponent_ICollectionsStatics> {
        get throws {
            try _lazyICollectionsStatics.lazyInitInterop {
                try _iactivationFactory.queryInterface(uuidof(SWRT_WinRTComponent_ICollectionsStatics.self)).cast()
            }
        }
    }
}