// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public struct Enum: RawRepresentable, Codable, Hashable, Sendable {
    public var rawValue: Swift.Int32

    public init(rawValue: Swift.Int32 = 0) {
        self.rawValue = rawValue
    }

    public static let minusOne = Self(rawValue: -1)
    public static let zero = Self()
    public static let int32Max = Self(rawValue: 2147483647)
}