// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public enum Errors {
    // MARK: WinRTComponent.IErrorsStatics members

    public static func failWith(_ hr: COM.HResult, _ message: Swift.String) throws {
        try _ierrorsStatics.failWith(hr, message)
    }

    public static func call(_ callee: MinimalDelegate?) throws {
        try _ierrorsStatics.call(callee)
    }

    public static func catchHResult(_ callee: MinimalDelegate?) throws -> COM.HResult {
        try _ierrorsStatics.catchHResult(callee)
    }

    public static func catchMessage(_ callee: MinimalDelegate?) throws -> Swift.String {
        try _ierrorsStatics.catchMessage(callee)
    }

    public static var notImplementedProperty: Swift.String {
        get {
            try! Self._notImplementedProperty()
        }
        set {
            try! Self._notImplementedProperty(newValue)
        }
    }

    public static func _notImplementedProperty() throws -> Swift.String {
        try _ierrorsStatics.get_NotImplementedProperty()
    }

    public static func _notImplementedProperty(_ value: Swift.String) throws {
        try _ierrorsStatics.put_NotImplementedProperty(value)
    }

    // MARK: Implementation details

    private static var _lazyIActivationFactory: COM.COMReference<SWRT_IActivationFactory>.Optional = .init()

    private static var _iactivationFactory: COM.COMInterop<SWRT_IActivationFactory> {
        get throws {
            try _lazyIActivationFactory.lazyInitInterop {
                try WindowsRuntime.activationFactoryResolver.resolve(runtimeClass: "WinRTComponent.Errors")
            }
        }
    }

    private static var _lazyIErrorsStatics: COM.COMReference<SWRT_WinRTComponent_IErrorsStatics>.Optional = .none

    internal static var _ierrorsStatics: COM.COMInterop<SWRT_WinRTComponent_IErrorsStatics> {
        get throws {
            try _lazyIErrorsStatics.lazyInitInterop {
                try _iactivationFactory.queryInterface(uuidof(SWRT_WinRTComponent_IErrorsStatics.self)).cast()
            }
        }
    }
}