// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public enum Events {
    // MARK: WinRTComponent.IEventsStatics members

    public static func createSource() throws -> IEventSource {
        try COM.NullResult.unwrap(_ieventsStatics.createSource())
    }

    public static func createCounter(_ source: IEventSource?) throws -> IEventCounter {
        try COM.NullResult.unwrap(_ieventsStatics.createCounter(source))
    }

    // MARK: Implementation details

    private static var _lazyIActivationFactory: COM.COMReference<SWRT_IActivationFactory>.Optional = .init()

    private static var _iactivationFactory: COM.COMInterop<SWRT_IActivationFactory> {
        get throws {
            try _lazyIActivationFactory.lazyInitInterop {
                try WindowsRuntime.activationFactoryResolver.resolve(runtimeClass: "WinRTComponent.Events")
            }
        }
    }

    private static var _lazyIEventsStatics: COM.COMReference<SWRT_WinRTComponent_IEventsStatics>.Optional = .none

    internal static var _ieventsStatics: COM.COMInterop<SWRT_WinRTComponent_IEventsStatics> {
        get throws {
            try _lazyIEventsStatics.lazyInitInterop {
                try _iactivationFactory.queryInterface(uuidof(SWRT_WinRTComponent_IEventsStatics.self)).cast()
            }
        }
    }
}