// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public struct Flags: OptionSet, Codable, Hashable, Sendable {
    public var rawValue: Swift.UInt32

    public init(rawValue: Swift.UInt32 = 0) {
        self.rawValue = rawValue
    }

    public static let none = Self()
    public static let bit0 = Self(rawValue: 1)
    public static let bit16 = Self(rawValue: 65536)
    public static let all = Self(rawValue: 4294967295)
}