// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public enum ForCustomActivationFactoryResolution {
    // MARK: WinRTComponent.IForCustomActivationFactoryResolutionStatics members

    public static func method() throws {
        try _iforCustomActivationFactoryResolutionStatics.method()
    }

    // MARK: Implementation details

    private static var _lazyIActivationFactory: COM.COMReference<SWRT_IActivationFactory>.Optional = .init()

    private static var _iactivationFactory: COM.COMInterop<SWRT_IActivationFactory> {
        get throws {
            try _lazyIActivationFactory.lazyInitInterop {
                try WindowsRuntime.activationFactoryResolver.resolve(runtimeClass: "WinRTComponent.ForCustomActivationFactoryResolution")
            }
        }
    }

    private static var _lazyIForCustomActivationFactoryResolutionStatics: COM.COMReference<SWRT_WinRTComponent_IForCustomActivationFactoryResolutionStatics>.Optional = .none

    internal static var _iforCustomActivationFactoryResolutionStatics: COM.COMInterop<SWRT_WinRTComponent_IForCustomActivationFactoryResolutionStatics> {
        get throws {
            try _lazyIForCustomActivationFactoryResolutionStatics.lazyInitInterop {
                try _iactivationFactory.queryInterface(uuidof(SWRT_WinRTComponent_IForCustomActivationFactoryResolutionStatics.self)).cast()
            }
        }
    }
}