// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public typealias IEventSource = any IEventSourceProtocol

public protocol IEventSourceProtocol: IInspectableProtocol {
    func fire() throws
    func event(adding handler: MinimalDelegate?) throws -> WindowsRuntime.EventRegistration
    func event(removing token: WindowsRuntime.EventRegistrationToken) throws
}