// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public typealias IEventCounter = any IEventCounterProtocol

public protocol IEventCounterProtocol: IInspectableProtocol {
    func detach() throws
    func _count() throws -> Swift.Int32
}

extension IEventCounterProtocol {
    public var count: Swift.Int32 {
        try! self._count()
    }
}