// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public typealias IMinimalInterface = any IMinimalInterfaceProtocol

public protocol IMinimalInterfaceProtocol: IInspectableProtocol {
    func method() throws
}