// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public enum Int32Global {
    // MARK: WinRTComponent.IInt32GlobalStatics members

    public static var getOnly: Swift.Int32 {
        try! Self._getOnly()
    }

    public static func _getOnly() throws -> Swift.Int32 {
        try _iint32GlobalStatics.get_GetOnly()
    }

    public static var getSet: Swift.Int32 {
        get {
            try! Self._getSet()
        }
        set {
            try! Self._getSet(newValue)
        }
    }

    public static func _getSet() throws -> Swift.Int32 {
        try _iint32GlobalStatics.get_GetSet()
    }

    public static func _getSet(_ value: Swift.Int32) throws {
        try _iint32GlobalStatics.put_GetSet(value)
    }

    // MARK: Implementation details

    private static var _lazyIActivationFactory: COM.COMReference<SWRT_IActivationFactory>.Optional = .init()

    private static var _iactivationFactory: COM.COMInterop<SWRT_IActivationFactory> {
        get throws {
            try _lazyIActivationFactory.lazyInitInterop {
                try WindowsRuntime.activationFactoryResolver.resolve(runtimeClass: "WinRTComponent.Int32Global")
            }
        }
    }

    private static var _lazyIInt32GlobalStatics: COM.COMReference<SWRT_WinRTComponent_IInt32GlobalStatics>.Optional = .none

    internal static var _iint32GlobalStatics: COM.COMInterop<SWRT_WinRTComponent_IInt32GlobalStatics> {
        get throws {
            try _lazyIInt32GlobalStatics.lazyInitInterop {
                try _iactivationFactory.queryInterface(uuidof(SWRT_WinRTComponent_IInt32GlobalStatics.self)).cast()
            }
        }
    }
}