// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public enum InterfaceCasting {
    // MARK: WinRTComponent.IInterfaceCastingStatics members

    public static func asMinimalInterface(_ object: WindowsRuntime.IInspectable?) throws -> IMinimalInterface {
        try COM.NullResult.unwrap(_iinterfaceCastingStatics.asMinimalInterface(object))
    }

    // MARK: Implementation details

    private static var _lazyIActivationFactory: COM.COMReference<SWRT_IActivationFactory>.Optional = .init()

    private static var _iactivationFactory: COM.COMInterop<SWRT_IActivationFactory> {
        get throws {
            try _lazyIActivationFactory.lazyInitInterop {
                try WindowsRuntime.activationFactoryResolver.resolve(runtimeClass: "WinRTComponent.InterfaceCasting")
            }
        }
    }

    private static var _lazyIInterfaceCastingStatics: COM.COMReference<SWRT_WinRTComponent_IInterfaceCastingStatics>.Optional = .none

    internal static var _iinterfaceCastingStatics: COM.COMInterop<SWRT_WinRTComponent_IInterfaceCastingStatics> {
        get throws {
            try _lazyIInterfaceCastingStatics.lazyInitInterop {
                try _iactivationFactory.queryInterface(uuidof(SWRT_WinRTComponent_IInterfaceCastingStatics.self)).cast()
            }
        }
    }
}