// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public typealias IOutputArgument = any IOutputArgumentProtocol

public protocol IOutputArgumentProtocol: IInspectableProtocol {
    func int32(_ value: Swift.Int32, _ result: inout Swift.Int32) throws
    func string(_ value: Swift.String, _ result: inout Swift.String) throws
    func object(_ value: WindowsRuntime.IInspectable?, _ result: inout WindowsRuntime.IInspectable?) throws
    func `enum`(_ value: MinimalEnum, _ result: inout MinimalEnum) throws
    func `struct`(_ value: MinimalStruct, _ result: inout MinimalStruct) throws
    func interface(_ value: IMinimalInterface?, _ result: inout IMinimalInterface?) throws
    func `class`(_ value: MinimalClass?, _ result: inout MinimalClass?) throws
    func delegate(_ value: MinimalDelegate?, _ result: inout MinimalDelegate?) throws
    func array(_ value: [Swift.String], _ result: inout [Swift.String]) throws
    func reference(_ value: Swift.Int32?, _ result: inout Swift.Int32?) throws
}