// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public typealias IReturnArgument = any IReturnArgumentProtocol

public protocol IReturnArgumentProtocol: IInspectableProtocol {
    func int32(_ value: Swift.Int32) throws -> Swift.Int32
    func string(_ value: Swift.String) throws -> Swift.String
    func object(_ value: WindowsRuntime.IInspectable?) throws -> WindowsRuntime.IInspectable
    func `enum`(_ value: MinimalEnum) throws -> MinimalEnum
    func `struct`(_ value: MinimalStruct) throws -> MinimalStruct
    func interface(_ value: IMinimalInterface?) throws -> IMinimalInterface
    func `class`(_ value: MinimalClass?) throws -> MinimalClass
    func delegate(_ value: MinimalDelegate?) throws -> MinimalDelegate
    func array(_ value: [Swift.String]) throws -> [Swift.String]
    func reference(_ value: Swift.Int32?) throws -> Swift.Int32?
}