// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public struct LeafStruct: Codable, Hashable, Sendable {
    public var int32: Swift.Int32
    public var string: Swift.String
    public var reference: Swift.Int32?

    public init() {
        self.int32 = 0
        self.string = ""
        self.reference = nil
    }

    public init(int32: Swift.Int32, string: Swift.String, reference: Swift.Int32?) {
        self.int32 = int32
        self.string = string
        self.reference = reference
    }
}