// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public final class MinimalClass: WindowsRuntime.WinRTImport<MinimalClassBinding>, @unchecked Sendable {
    // MARK: IActivationFactory members

    public convenience init() throws {
        self.init(_wrapping: COM.COMReference(transferringRef: try Self._iactivationFactory.activateInstance(binding: MinimalClassBinding.self)))
    }

    // MARK: WinRTComponent.IMinimalClass members

    public func method() throws {
        try _interop.method()
    }

    // MARK: Implementation details

    private static var _lazyIActivationFactory: COM.COMReference<SWRT_IActivationFactory>.Optional = .init()

    private static var _iactivationFactory: COM.COMInterop<SWRT_IActivationFactory> {
        get throws {
            try _lazyIActivationFactory.lazyInitInterop {
                try WindowsRuntime.activationFactoryResolver.resolve(runtimeClass: "WinRTComponent.MinimalClass")
            }
        }
    }
}