// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

open class MinimalDerivedClass: MinimalBaseClass, @unchecked Sendable {
    // MARK: WinRTComponent.IMinimalDerivedClassFactory members

    public override init() throws {
        try super.init(_compose: Self.self != MinimalDerivedClass.self) {
            (baseInterface, innerInterface: inout IInspectablePointer?) in
            try Self._iminimalDerivedClassFactory.createInstance(baseInterface, &innerInterface)
        }
    }

    // MARK: WinRTComponent.IMinimalDerivedClassStatics members

    public static func createDerived() throws -> MinimalDerivedClass {
        try COM.NullResult.unwrap(_iminimalDerivedClassStatics.createDerived())
    }

    // MARK: Implementation details

    private var _lazyIMinimalDerivedClass: COM.COMReference<SWRT_WinRTComponent_IMinimalDerivedClass>.Optional = .none

    internal var _iminimalDerivedClass: COM.COMInterop<SWRT_WinRTComponent_IMinimalDerivedClass> {
        get throws {
            try _lazyIMinimalDerivedClass.lazyInitInterop {
                try _queryInnerInterface(uuidof(SWRT_WinRTComponent_IMinimalDerivedClass.self)).cast()
            }
        }
    }

    public init(_wrapping inner: consuming COM.COMReference<SWRT_WinRTComponent_IMinimalDerivedClass>) {
        super.init(_wrapping: inner.cast()) // Transitively casts down to IInspectable
    }

    public override init<ABIStruct>(_compose: Swift.Bool, _factory: ComposableFactory<ABIStruct>) throws {
        try super.init(_compose: _compose, _factory: _factory)
    }

    private static var _lazyIActivationFactory: COM.COMReference<SWRT_IActivationFactory>.Optional = .init()

    private static var _iactivationFactory: COM.COMInterop<SWRT_IActivationFactory> {
        get throws {
            try _lazyIActivationFactory.lazyInitInterop {
                try WindowsRuntime.activationFactoryResolver.resolve(runtimeClass: "WinRTComponent.MinimalDerivedClass")
            }
        }
    }

    private static var _lazyIMinimalDerivedClassFactory: COM.COMReference<SWRT_WinRTComponent_IMinimalDerivedClassFactory>.Optional = .none

    internal static var _iminimalDerivedClassFactory: COM.COMInterop<SWRT_WinRTComponent_IMinimalDerivedClassFactory> {
        get throws {
            try _lazyIMinimalDerivedClassFactory.lazyInitInterop {
                try _iactivationFactory.queryInterface(uuidof(SWRT_WinRTComponent_IMinimalDerivedClassFactory.self)).cast()
            }
        }
    }

    private static var _lazyIMinimalDerivedClassStatics: COM.COMReference<SWRT_WinRTComponent_IMinimalDerivedClassStatics>.Optional = .none

    internal static var _iminimalDerivedClassStatics: COM.COMInterop<SWRT_WinRTComponent_IMinimalDerivedClassStatics> {
        get throws {
            try _lazyIMinimalDerivedClassStatics.lazyInitInterop {
                try _iactivationFactory.queryInterface(uuidof(SWRT_WinRTComponent_IMinimalDerivedClassStatics.self)).cast()
            }
        }
    }
}