// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public enum MinimalInterfaceFactory {
    // MARK: WinRTComponent.IMinimalInterfaceFactoryStatics members

    public static func create() throws -> IMinimalInterface {
        try COM.NullResult.unwrap(_iminimalInterfaceFactoryStatics.create())
    }

    // MARK: Implementation details

    private static var _lazyIActivationFactory: COM.COMReference<SWRT_IActivationFactory>.Optional = .init()

    private static var _iactivationFactory: COM.COMInterop<SWRT_IActivationFactory> {
        get throws {
            try _lazyIActivationFactory.lazyInitInterop {
                try WindowsRuntime.activationFactoryResolver.resolve(runtimeClass: "WinRTComponent.MinimalInterfaceFactory")
            }
        }
    }

    private static var _lazyIMinimalInterfaceFactoryStatics: COM.COMReference<SWRT_WinRTComponent_IMinimalInterfaceFactoryStatics>.Optional = .none

    internal static var _iminimalInterfaceFactoryStatics: COM.COMInterop<SWRT_WinRTComponent_IMinimalInterfaceFactoryStatics> {
        get throws {
            try _lazyIMinimalInterfaceFactoryStatics.lazyInitInterop {
                try _iactivationFactory.queryInterface(uuidof(SWRT_WinRTComponent_IMinimalInterfaceFactoryStatics.self)).cast()
            }
        }
    }
}