// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public struct MinimalStruct: Codable, Hashable, Sendable {
    public var field: Swift.Int32

    public init() {
        self.field = 0
    }

    public init(field: Swift.Int32) {
        self.field = field
    }
}