// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public enum NullValues {
    // MARK: WinRTComponent.INullValuesStatics members

    public static func isObjectNull(_ value: WindowsRuntime.IInspectable?) throws -> Swift.Bool {
        try _inullValuesStatics.isObjectNull(value)
    }

    public static func isInterfaceNull(_ value: IMinimalInterface?) throws -> Swift.Bool {
        try _inullValuesStatics.isInterfaceNull(value)
    }

    public static func isClassNull(_ value: MinimalClass?) throws -> Swift.Bool {
        try _inullValuesStatics.isClassNull(value)
    }

    public static func isDelegateNull(_ value: MinimalDelegate?) throws -> Swift.Bool {
        try _inullValuesStatics.isDelegateNull(value)
    }

    public static func isReferenceNull(_ value: Swift.Int32?) throws -> Swift.Bool {
        try _inullValuesStatics.isReferenceNull(value)
    }

    public static func getNullObject() throws -> WindowsRuntime.IInspectable {
        try COM.NullResult.unwrap(_inullValuesStatics.getNullObject())
    }

    public static func getNullInterface() throws -> IMinimalInterface {
        try COM.NullResult.unwrap(_inullValuesStatics.getNullInterface())
    }

    public static func getNullClass() throws -> MinimalClass {
        try COM.NullResult.unwrap(_inullValuesStatics.getNullClass())
    }

    public static func getNullDelegate() throws -> MinimalDelegate {
        try COM.NullResult.unwrap(_inullValuesStatics.getNullDelegate())
    }

    public static func getNullReference() throws -> Swift.Int32? {
        try _inullValuesStatics.getNullReference()
    }

    // MARK: Implementation details

    private static var _lazyIActivationFactory: COM.COMReference<SWRT_IActivationFactory>.Optional = .init()

    private static var _iactivationFactory: COM.COMInterop<SWRT_IActivationFactory> {
        get throws {
            try _lazyIActivationFactory.lazyInitInterop {
                try WindowsRuntime.activationFactoryResolver.resolve(runtimeClass: "WinRTComponent.NullValues")
            }
        }
    }

    private static var _lazyINullValuesStatics: COM.COMReference<SWRT_WinRTComponent_INullValuesStatics>.Optional = .none

    internal static var _inullValuesStatics: COM.COMInterop<SWRT_WinRTComponent_INullValuesStatics> {
        get throws {
            try _lazyINullValuesStatics.lazyInitInterop {
                try _iactivationFactory.queryInterface(uuidof(SWRT_WinRTComponent_INullValuesStatics.self)).cast()
            }
        }
    }
}