// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public enum Numbers {
    // MARK: WinRTComponent.INumbersStatics members

    public static func not(_ value: Swift.Bool) throws -> Swift.Bool {
        try _inumbersStatics.not(value)
    }

    public static func incrementUInt8(_ value: Swift.UInt8) throws -> Swift.UInt8 {
        try _inumbersStatics.incrementUInt8(value)
    }

    public static func incrementInt16(_ value: Swift.Int16) throws -> Swift.Int16 {
        try _inumbersStatics.incrementInt16(value)
    }

    public static func incrementUInt16(_ value: Swift.UInt16) throws -> Swift.UInt16 {
        try _inumbersStatics.incrementUInt16(value)
    }

    public static func incrementInt32(_ value: Swift.Int32) throws -> Swift.Int32 {
        try _inumbersStatics.incrementInt32(value)
    }

    public static func incrementUInt32(_ value: Swift.UInt32) throws -> Swift.UInt32 {
        try _inumbersStatics.incrementUInt32(value)
    }

    public static func incrementInt64(_ value: Swift.Int64) throws -> Swift.Int64 {
        try _inumbersStatics.incrementInt64(value)
    }

    public static func incrementUInt64(_ value: Swift.UInt64) throws -> Swift.UInt64 {
        try _inumbersStatics.incrementUInt64(value)
    }

    public static func negateSingle(_ value: Swift.Float) throws -> Swift.Float {
        try _inumbersStatics.negateSingle(value)
    }

    public static func negateDouble(_ value: Swift.Double) throws -> Swift.Double {
        try _inumbersStatics.negateDouble(value)
    }

    // MARK: Implementation details

    private static var _lazyIActivationFactory: COM.COMReference<SWRT_IActivationFactory>.Optional = .init()

    private static var _iactivationFactory: COM.COMInterop<SWRT_IActivationFactory> {
        get throws {
            try _lazyIActivationFactory.lazyInitInterop {
                try WindowsRuntime.activationFactoryResolver.resolve(runtimeClass: "WinRTComponent.Numbers")
            }
        }
    }

    private static var _lazyINumbersStatics: COM.COMReference<SWRT_WinRTComponent_INumbersStatics>.Optional = .none

    internal static var _inumbersStatics: COM.COMInterop<SWRT_WinRTComponent_INumbersStatics> {
        get throws {
            try _lazyINumbersStatics.lazyInitInterop {
                try _iactivationFactory.queryInterface(uuidof(SWRT_WinRTComponent_INumbersStatics.self)).cast()
            }
        }
    }
}