// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public final class ObjectReferencer: WindowsRuntime.WinRTImport<ObjectReferencerBinding>, @unchecked Sendable {
    // MARK: WinRTComponent.IObjectReferencerFactory members

    public convenience init(_ obj: WindowsRuntime.IInspectable?) throws {
        self.init(_wrapping: try Self._iobjectReferencerFactory.createInstance(obj))
    }

    // MARK: WinRTComponent.IObjectReferencer members

    public func callAddRef() throws -> Swift.UInt32 {
        try _interop.callAddRef()
    }

    public func callRelease() throws -> Swift.UInt32 {
        try _interop.callRelease()
    }

    public func clear() throws {
        try _interop.clear()
    }

    public var target: WindowsRuntime.IInspectable! {
        try! NullResult.catch(self._target())
    }

    public func _target() throws -> WindowsRuntime.IInspectable {
        try COM.NullResult.unwrap(_interop.get_Target())
    }

    // MARK: Implementation details

    private static var _lazyIActivationFactory: COM.COMReference<SWRT_IActivationFactory>.Optional = .init()

    private static var _iactivationFactory: COM.COMInterop<SWRT_IActivationFactory> {
        get throws {
            try _lazyIActivationFactory.lazyInitInterop {
                try WindowsRuntime.activationFactoryResolver.resolve(runtimeClass: "WinRTComponent.ObjectReferencer")
            }
        }
    }

    private static var _lazyIObjectReferencerFactory: COM.COMReference<SWRT_WinRTComponent_IObjectReferencerFactory>.Optional = .none

    internal static var _iobjectReferencerFactory: COM.COMInterop<SWRT_WinRTComponent_IObjectReferencerFactory> {
        get throws {
            try _lazyIObjectReferencerFactory.lazyInitInterop {
                try _iactivationFactory.queryInterface(uuidof(SWRT_WinRTComponent_IObjectReferencerFactory.self)).cast()
            }
        }
    }
}