// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public enum OutputArgument {
    // MARK: WinRTComponent.IOutputArgumentStatics members

    public static func create() throws -> IOutputArgument {
        try COM.NullResult.unwrap(_ioutputArgumentStatics.create())
    }

    public static func createProxy(_ inner: IOutputArgument?) throws -> IOutputArgument {
        try COM.NullResult.unwrap(_ioutputArgumentStatics.createProxy(inner))
    }

    // MARK: Implementation details

    private static var _lazyIActivationFactory: COM.COMReference<SWRT_IActivationFactory>.Optional = .init()

    private static var _iactivationFactory: COM.COMInterop<SWRT_IActivationFactory> {
        get throws {
            try _lazyIActivationFactory.lazyInitInterop {
                try WindowsRuntime.activationFactoryResolver.resolve(runtimeClass: "WinRTComponent.OutputArgument")
            }
        }
    }

    private static var _lazyIOutputArgumentStatics: COM.COMReference<SWRT_WinRTComponent_IOutputArgumentStatics>.Optional = .none

    internal static var _ioutputArgumentStatics: COM.COMInterop<SWRT_WinRTComponent_IOutputArgumentStatics> {
        get throws {
            try _lazyIOutputArgumentStatics.lazyInitInterop {
                try _iactivationFactory.queryInterface(uuidof(SWRT_WinRTComponent_IOutputArgumentStatics.self)).cast()
            }
        }
    }
}