// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public enum ReturnArgument {
    // MARK: WinRTComponent.IReturnArgumentStatics members

    public static func create() throws -> IReturnArgument {
        try COM.NullResult.unwrap(_ireturnArgumentStatics.create())
    }

    public static func createProxy(_ inner: IReturnArgument?) throws -> IReturnArgument {
        try COM.NullResult.unwrap(_ireturnArgumentStatics.createProxy(inner))
    }

    // MARK: Implementation details

    private static var _lazyIActivationFactory: COM.COMReference<SWRT_IActivationFactory>.Optional = .init()

    private static var _iactivationFactory: COM.COMInterop<SWRT_IActivationFactory> {
        get throws {
            try _lazyIActivationFactory.lazyInitInterop {
                try WindowsRuntime.activationFactoryResolver.resolve(runtimeClass: "WinRTComponent.ReturnArgument")
            }
        }
    }

    private static var _lazyIReturnArgumentStatics: COM.COMReference<SWRT_WinRTComponent_IReturnArgumentStatics>.Optional = .none

    internal static var _ireturnArgumentStatics: COM.COMInterop<SWRT_WinRTComponent_IReturnArgumentStatics> {
        get throws {
            try _lazyIReturnArgumentStatics.lazyInitInterop {
                try _iactivationFactory.queryInterface(uuidof(SWRT_WinRTComponent_IReturnArgumentStatics.self)).cast()
            }
        }
    }
}