// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public enum Strings {
    // MARK: WinRTComponent.IStringsStatics members

    public static func roundtrip(_ value: Swift.String) throws -> Swift.String {
        try _istringsStatics.roundtrip(value)
    }

    public static func roundtripChar(_ value: WindowsRuntime.Char16) throws -> WindowsRuntime.Char16 {
        try _istringsStatics.roundtripChar(value)
    }

    public static func fromChars(_ chars: [WindowsRuntime.Char16]) throws -> Swift.String {
        try _istringsStatics.fromChars(chars)
    }

    public static func toChars(_ value: Swift.String) throws -> [WindowsRuntime.Char16] {
        try _istringsStatics.toChars(value)
    }

    // MARK: Implementation details

    private static var _lazyIActivationFactory: COM.COMReference<SWRT_IActivationFactory>.Optional = .init()

    private static var _iactivationFactory: COM.COMInterop<SWRT_IActivationFactory> {
        get throws {
            try _lazyIActivationFactory.lazyInitInterop {
                try WindowsRuntime.activationFactoryResolver.resolve(runtimeClass: "WinRTComponent.Strings")
            }
        }
    }

    private static var _lazyIStringsStatics: COM.COMReference<SWRT_WinRTComponent_IStringsStatics>.Optional = .none

    internal static var _istringsStatics: COM.COMInterop<SWRT_WinRTComponent_IStringsStatics> {
        get throws {
            try _lazyIStringsStatics.lazyInitInterop {
                try _iactivationFactory.queryInterface(uuidof(SWRT_WinRTComponent_IStringsStatics.self)).cast()
            }
        }
    }
}