// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public struct Struct: Codable, Hashable, Sendable {
    public var int32: Swift.Int32
    public var string: Swift.String
    public var reference: Swift.Int32?
    public var nested: LeafStruct

    public init() {
        self.int32 = 0
        self.string = ""
        self.reference = nil
        self.nested = .init()
    }

    public init(int32: Swift.Int32, string: Swift.String, reference: Swift.Int32?, nested: LeafStruct) {
        self.int32 = int32
        self.string = string
        self.reference = reference
        self.nested = nested
    }
}