// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public enum Structs {
    // MARK: WinRTComponent.IStructsStatics members

    public static func make(_ int32: Swift.Int32, _ string: Swift.String, _ reference: Swift.Int32?, _ nested: LeafStruct) throws -> Struct {
        try _istructsStatics.make(int32, string, reference, nested)
    }

    public static func getInt32(_ value: Struct) throws -> Swift.Int32 {
        try _istructsStatics.getInt32(value)
    }

    public static func getString(_ value: Struct) throws -> Swift.String {
        try _istructsStatics.getString(value)
    }

    public static func getReference(_ value: Struct) throws -> Swift.Int32? {
        try _istructsStatics.getReference(value)
    }

    public static func getNested(_ value: Struct) throws -> LeafStruct {
        try _istructsStatics.getNested(value)
    }

    public static func output(_ int32: Swift.Int32, _ string: Swift.String, _ reference: Swift.Int32?, _ nested: LeafStruct, _ value: inout Struct) throws {
        try _istructsStatics.output(int32, string, reference, nested, &value)
    }

    public static func returnRefConstArgument(_ value: Struct) throws -> Struct {
        try _istructsStatics.returnRefConstArgument(value)
    }

    // MARK: Implementation details

    private static var _lazyIActivationFactory: COM.COMReference<SWRT_IActivationFactory>.Optional = .init()

    private static var _iactivationFactory: COM.COMInterop<SWRT_IActivationFactory> {
        get throws {
            try _lazyIActivationFactory.lazyInitInterop {
                try WindowsRuntime.activationFactoryResolver.resolve(runtimeClass: "WinRTComponent.Structs")
            }
        }
    }

    private static var _lazyIStructsStatics: COM.COMReference<SWRT_WinRTComponent_IStructsStatics>.Optional = .none

    internal static var _istructsStatics: COM.COMInterop<SWRT_WinRTComponent_IStructsStatics> {
        get throws {
            try _lazyIStructsStatics.lazyInitInterop {
                try _iactivationFactory.queryInterface(uuidof(SWRT_WinRTComponent_IStructsStatics.self)).cast()
            }
        }
    }
}