// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public enum SwiftEnum: Swift.Int32, Codable, Hashable, Sendable {
    case zero = 0
    case one = 1
}