// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import WinRTComponent_ABI
import UWP

public enum SwiftAttributes {
    // MARK: WinRTComponent.ISwiftAttributesStatics members

    @MainActor
    public static func mainActor() throws {
        try _iswiftAttributesStatics.mainActor()
    }

    @available(swift 1)
    public static func availableFromSwift1() throws {
        try _iswiftAttributesStatics.availableFromSwift1()
    }

    @discardableResult
    @available(swift 1)
    public static func availableFromSwift1WithDiscardableResult() throws -> Swift.Int32 {
        try _iswiftAttributesStatics.availableFromSwift1WithDiscardableResult()
    }

    // MARK: Implementation details

    private static var _lazyIActivationFactory: COM.COMReference<SWRT_IActivationFactory>.Optional = .init()

    private static var _iactivationFactory: COM.COMInterop<SWRT_IActivationFactory> {
        get throws {
            try _lazyIActivationFactory.lazyInitInterop {
                try WindowsRuntime.activationFactoryResolver.resolve(runtimeClass: "WinRTComponent.SwiftAttributes")
            }
        }
    }

    private static var _lazyISwiftAttributesStatics: COM.COMReference<SWRT_WinRTComponent_ISwiftAttributesStatics>.Optional = .none

    internal static var _iswiftAttributesStatics: COM.COMInterop<SWRT_WinRTComponent_ISwiftAttributesStatics> {
        get throws {
            try _lazyISwiftAttributesStatics.lazyInitInterop {
                try _iactivationFactory.queryInterface(uuidof(SWRT_WinRTComponent_ISwiftAttributesStatics.self)).cast()
            }
        }
    }
}