// Generated by swift-winrt
// swiftlint:disable all

import UWP

public typealias Buffer = WindowsStorageStreams_Buffer
public typealias IBuffer = WindowsStorageStreams_IBuffer

public protocol IBufferProtocol: WindowsStorageStreams_IBufferProtocol {
}

public typealias IBufferBinding = WindowsStorageStreams_IBufferBinding