// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import UWP_ABI

/// Represents a referenced array of bytes used by byte stream read and write interfaces. Buffer is the class implementation of this interface.
public typealias WindowsStorageStreams_IBuffer = any WindowsStorageStreams_IBufferProtocol

/// Represents a referenced array of bytes used by byte stream read and write interfaces. Buffer is the class implementation of this interface.
public protocol WindowsStorageStreams_IBufferProtocol: IInspectableProtocol {
    /// Gets the maximum number of bytes that the buffer can hold.
    /// - Returns: The maximum number of bytes that the buffer can hold.
    func _capacity() throws -> Swift.UInt32

    /// Gets the number of bytes currently in use in the buffer.
    /// - Returns: The number of bytes currently in use in the buffer which is less than or equal to the capacity of the buffer.
    func _length() throws -> Swift.UInt32

    func _length(_ value: Swift.UInt32) throws
}

extension WindowsStorageStreams_IBufferProtocol {
    /// Gets the maximum number of bytes that the buffer can hold.
    /// - Returns: The maximum number of bytes that the buffer can hold.
    public var capacity: Swift.UInt32 {
        try! self._capacity()
    }

    /// Gets the number of bytes currently in use in the buffer.
    /// - Returns: The number of bytes currently in use in the buffer which is less than or equal to the capacity of the buffer.
    public var length: Swift.UInt32 {
        get {
            try! self._length()
        }
        set {
            try! self._length(newValue)
        }
    }
}