// Generated by swift-winrt
// swiftlint:disable all

import WindowsRuntime
import UWP_ABI

/// Provides a default implementation of the IBuffer interface and its related interfaces.
public final class WindowsStorageStreams_Buffer: WindowsRuntime.WinRTImport<WindowsStorageStreams_BufferBinding>, WindowsStorageStreams_IBufferProtocol, @unchecked Sendable {
    // MARK: Windows.Storage.Streams.IBufferFactory members

    public convenience init(_ capacity: Swift.UInt32) throws {
        self.init(_wrapping: try Self._ibufferFactory.create(capacity))
    }

    // MARK: Windows.Storage.Streams.IBuffer members

    /// Gets the maximum number of bytes that the buffer can hold.
    /// - Returns: The maximum number of bytes that the buffer can hold.
    public func _capacity() throws -> Swift.UInt32 {
        try _interop.get_Capacity()
    }

    /// Gets the number of bytes currently in use in the buffer.
    /// - Returns: The number of bytes currently in use in the buffer, which is less than or equal to the capacity of the buffer.
    public func _length() throws -> Swift.UInt32 {
        try _interop.get_Length()
    }

    /// Gets the number of bytes currently in use in the buffer.
    /// - Returns: The number of bytes currently in use in the buffer, which is less than or equal to the capacity of the buffer.
    public func _length(_ value: Swift.UInt32) throws {
        try _interop.put_Length(value)
    }

    // MARK: Windows.Storage.Streams.IBufferStatics members

    /// Creates a new buffer containing a copy of a specified buffer.
    /// - Parameter input: The buffer to be copied.
    /// - Returns: The newly created copy.
    public static func createCopyFromMemoryBuffer(_ input: WindowsFoundation_IMemoryBuffer?) throws -> WindowsStorageStreams_Buffer {
        try COM.NullResult.unwrap(_ibufferStatics.createCopyFromMemoryBuffer(input))
    }

    /// Creates a MemoryBuffer from an existing IBuffer.
    /// - Parameter input: The input IBuffer.
    /// - Returns: The newly created MemoryBuffer.
    public static func createMemoryBufferOverIBuffer(_ input: WindowsStorageStreams_IBuffer?) throws -> WindowsFoundation_MemoryBuffer {
        try COM.NullResult.unwrap(_ibufferStatics.createMemoryBufferOverIBuffer(input))
    }

    // MARK: Implementation details

    private static var _lazyIActivationFactory: COM.COMReference<SWRT_IActivationFactory>.Optional = .init()

    private static var _iactivationFactory: COM.COMInterop<SWRT_IActivationFactory> {
        get throws {
            try _lazyIActivationFactory.lazyInitInterop {
                try WindowsRuntime.activationFactoryResolver.resolve(runtimeClass: "Windows.Storage.Streams.Buffer")
            }
        }
    }

    private static var _lazyIBufferFactory: COM.COMReference<SWRT_WindowsStorageStreams_IBufferFactory>.Optional = .none

    internal static var _ibufferFactory: COM.COMInterop<SWRT_WindowsStorageStreams_IBufferFactory> {
        get throws {
            try _lazyIBufferFactory.lazyInitInterop {
                try _iactivationFactory.queryInterface(uuidof(SWRT_WindowsStorageStreams_IBufferFactory.self)).cast()
            }
        }
    }

    private static var _lazyIBufferStatics: COM.COMReference<SWRT_WindowsStorageStreams_IBufferStatics>.Optional = .none

    internal static var _ibufferStatics: COM.COMInterop<SWRT_WindowsStorageStreams_IBufferStatics> {
        get throws {
            try _lazyIBufferStatics.lazyInitInterop {
                try _iactivationFactory.queryInterface(uuidof(SWRT_WindowsStorageStreams_IBufferStatics.self)).cast()
            }
        }
    }
}